import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Starting seed...');

  // Seed achievements
  const achievements = [
    { id: 'first-lesson', title: 'First Step', description: 'Complete your first lesson', icon: '🎯', xpReward: 50, condition: JSON.stringify({ type: 'lessons_completed', count: 1 }) },
    { id: 'five-lessons', title: 'Getting Started', description: 'Complete 5 lessons', icon: '📚', xpReward: 100, condition: JSON.stringify({ type: 'lessons_completed', count: 5 }) },
    { id: 'ten-lessons', title: 'Dedicated Learner', description: 'Complete 10 lessons', icon: '🏆', xpReward: 200, condition: JSON.stringify({ type: 'lessons_completed', count: 10 }) },
    { id: 'fifty-lessons', title: 'Language Champion', description: 'Complete 50 lessons', icon: '👑', xpReward: 500, condition: JSON.stringify({ type: 'lessons_completed', count: 50 }) },
    { id: 'streak-3', title: 'On a Roll', description: 'Maintain a 3-day streak', icon: '🔥', xpReward: 75, condition: JSON.stringify({ type: 'streak', days: 3 }) },
    { id: 'streak-7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '⚡', xpReward: 150, condition: JSON.stringify({ type: 'streak', days: 7 }) },
    { id: 'streak-30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '💎', xpReward: 500, condition: JSON.stringify({ type: 'streak', days: 30 }) },
    { id: 'streak-100', title: 'Century Streak', description: 'Maintain a 100-day streak', icon: '🌟', xpReward: 2000, condition: JSON.stringify({ type: 'streak', days: 100 }) },
    { id: 'xp-500', title: 'Explorer', description: 'Earn 500 XP', icon: '🗺️', xpReward: 50, condition: JSON.stringify({ type: 'xp', amount: 500 }) },
    { id: 'xp-1500', title: 'Adventurer', description: 'Earn 1500 XP', icon: '⚔️', xpReward: 100, condition: JSON.stringify({ type: 'xp', amount: 1500 }) },
    { id: 'xp-5000', title: 'Scholar', description: 'Earn 5000 XP', icon: '🎓', xpReward: 200, condition: JSON.stringify({ type: 'xp', amount: 5000 }) },
    { id: 'xp-10000', title: 'Linguist', description: 'Earn 10000 XP', icon: '🧠', xpReward: 500, condition: JSON.stringify({ type: 'xp', amount: 10000 }) },
    { id: 'first-flashcard', title: 'Memory Maker', description: 'Review your first flashcard', icon: '🃏', xpReward: 25, condition: JSON.stringify({ type: 'flashcards_reviewed', count: 1 }) },
    { id: 'flashcards-100', title: 'Card Shark', description: 'Review 100 flashcards', icon: '🎴', xpReward: 150, condition: JSON.stringify({ type: 'flashcards_reviewed', count: 100 }) },
    { id: 'flashcards-500', title: 'Memory Palace', description: 'Review 500 flashcards', icon: '🏛️', xpReward: 300, condition: JSON.stringify({ type: 'flashcards_reviewed', count: 500 }) },
    { id: 'first-speaking', title: 'First Words', description: 'Complete first speaking session', icon: '🗣️', xpReward: 75, condition: JSON.stringify({ type: 'speaking_sessions', count: 1 }) },
    { id: 'speaking-10', title: 'Conversationalist', description: 'Complete 10 speaking sessions', icon: '💬', xpReward: 200, condition: JSON.stringify({ type: 'speaking_sessions', count: 10 }) },
    { id: 'first-writing', title: 'Pensmith', description: 'Write your first journal entry', icon: '✍️', xpReward: 50, condition: JSON.stringify({ type: 'writing_entries', count: 1 }) },
    { id: 'writing-10', title: 'Storyteller', description: 'Write 10 journal entries', icon: '📖', xpReward: 150, condition: JSON.stringify({ type: 'writing_entries', count: 10 }) },
    { id: 'perfect-lesson', title: 'Perfectionist', description: 'Get a perfect score on a lesson', icon: '💯', xpReward: 100, condition: JSON.stringify({ type: 'perfect_lesson', count: 1 }) },
    { id: 'perfect-5', title: 'Flawless', description: 'Get perfect scores on 5 lessons', icon: '✨', xpReward: 250, condition: JSON.stringify({ type: 'perfect_lesson', count: 5 }) },
    { id: 'daily-challenge', title: 'Daily Grind', description: 'Complete your first daily challenge', icon: '📅', xpReward: 60, condition: JSON.stringify({ type: 'daily_challenges', count: 1 }) },
    { id: 'daily-challenge-7', title: 'Challenge Accepted', description: 'Complete 7 daily challenges', icon: '🎯', xpReward: 200, condition: JSON.stringify({ type: 'daily_challenges', count: 7 }) },
    { id: 'leaderboard-top10', title: 'Rising Star', description: 'Reach top 10 on the leaderboard', icon: '⭐', xpReward: 300, condition: JSON.stringify({ type: 'leaderboard_rank', rank: 10 }) },
    { id: 'leaderboard-top3', title: 'Podium Finisher', description: 'Reach top 3 on the leaderboard', icon: '🥉', xpReward: 500, condition: JSON.stringify({ type: 'leaderboard_rank', rank: 3 }) },
    { id: 'leaderboard-1', title: 'Champion', description: 'Reach #1 on the leaderboard', icon: '🥇', xpReward: 1000, condition: JSON.stringify({ type: 'leaderboard_rank', rank: 1 }) },
    { id: 'night-owl', title: 'Night Owl', description: 'Study after midnight', icon: '🦉', xpReward: 50, condition: JSON.stringify({ type: 'study_time', hour: 0 }) },
    { id: 'early-bird', title: 'Early Bird', description: 'Study before 7am', icon: '🐦', xpReward: 50, condition: JSON.stringify({ type: 'study_time', hour: 7 }) },
    { id: 'weekend-warrior', title: 'Weekend Warrior', description: 'Study on both Saturday and Sunday', icon: '🏖️', xpReward: 100, condition: JSON.stringify({ type: 'weekend_study' }) },
    { id: 'all-unit1', title: 'Unit 1 Complete', description: 'Complete all lessons in Unit 1', icon: '🎊', xpReward: 200, condition: JSON.stringify({ type: 'unit_complete', unit: 1 }) },
  ];

  for (const ach of achievements) {
    await prisma.achievement.upsert({ where: { id: ach.id }, update: ach, create: ach });
  }
  console.log(`Seeded ${achievements.length} achievements`);

  const lessons = [
    {
      id: 'lesson-1-1',
      title: 'Basic Greetings',
      description: 'Learn essential Spanish greetings for any time of day',
      level: 'A1', unit: 1, order: 1, type: 'VOCABULARY', estimatedMinutes: 10, xpReward: 30,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'How do you say "Good morning" in Spanish?', options: ['Buenas noches', 'Buenos días', 'Buenas tardes', 'Hasta luego'], correctIndex: 1, explanation: 'Buenos días is used in the morning until noon.' },
        { type: 'multiple_choice', question: 'What does "¿Cómo estás?" mean?', options: ['What is your name?', 'Where are you from?', 'How are you?', 'How old are you?'], correctIndex: 2, explanation: '¿Cómo estás? is the informal way to ask "How are you?"' },
        { type: 'fill_blank', sentence: 'Hola, me llamo María. _____ gusto.', answer: 'Mucho', hint: 'This phrase means "Nice to meet you"' },
        { type: 'word_match', pairs: [{ left: 'Hola', right: 'Hello' }, { left: 'Adiós', right: 'Goodbye' }, { left: 'Por favor', right: 'Please' }, { left: 'Gracias', right: 'Thank you' }, { left: 'De nada', right: "You're welcome" }] },
        { type: 'multiple_choice', question: 'Which greeting is used in the evening?', options: ['Buenos días', 'Buenas tardes', 'Buenas noches', 'Hola'], correctIndex: 2, explanation: 'Buenas noches means "Good evening/Good night".' },
        { type: 'fill_blank', sentence: '_____ días, señor García.', answer: 'Buenos', hint: 'Morning greeting' },
        { type: 'multiple_choice', question: 'How do you say "See you later" in Spanish?', options: ['Hola', 'Gracias', 'Hasta luego', 'Por favor'], correctIndex: 2, explanation: 'Hasta luego means "Until later" or "See you later".' },
        { type: 'sentence_builder', words: ['llamo', 'Me', 'Carlos'], answer: 'Me llamo Carlos', translation: 'My name is Carlos' },
      ]}),
      flashcards: [
        { front: 'Hola', back: 'Hello', tags: 'greetings,basic' },
        { front: 'Adiós', back: 'Goodbye', tags: 'greetings,basic' },
        { front: 'Buenos días', back: 'Good morning', tags: 'greetings,time' },
        { front: 'Buenas tardes', back: 'Good afternoon', tags: 'greetings,time' },
        { front: 'Buenas noches', back: 'Good evening/night', tags: 'greetings,time' },
        { front: 'Por favor', back: 'Please', tags: 'courtesy,basic' },
        { front: 'Gracias', back: 'Thank you', tags: 'courtesy,basic' },
        { front: 'De nada', back: "You're welcome", tags: 'courtesy,basic' },
        { front: '¿Cómo estás?', back: 'How are you? (informal)', tags: 'greetings,questions' },
        { front: 'Mucho gusto', back: 'Nice to meet you', tags: 'greetings,courtesy' },
      ],
    },
    {
      id: 'lesson-1-2',
      title: 'Introducing Yourself',
      description: 'Learn how to introduce yourself and ask about others',
      level: 'A1', unit: 1, order: 2, type: 'SPEAKING', estimatedMinutes: 12, xpReward: 35,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: "How do you ask someone's name in Spanish?", options: ['¿Cómo estás?', '¿Cómo te llamas?', '¿De dónde eres?', '¿Cuántos años tienes?'], correctIndex: 1, explanation: '¿Cómo te llamas? means "What is your name?"' },
        { type: 'fill_blank', sentence: 'Me _____ Ana. Soy de México.', answer: 'llamo', hint: 'Use the verb llamarse (to be named)' },
        { type: 'multiple_choice', question: 'How do you say "I am from Spain"?', options: ['Soy España', 'Estoy de España', 'Soy de España', 'Vengo España'], correctIndex: 2, explanation: 'Use "Soy de + country" to say where you are from.' },
        { type: 'sentence_builder', words: ['de', 'Soy', 'Colombia'], answer: 'Soy de Colombia', translation: 'I am from Colombia' },
        { type: 'fill_blank', sentence: 'Yo tengo veinte _____.', answer: 'años', hint: 'Word for years' },
        { type: 'multiple_choice', question: 'What does "¿De dónde eres?" mean?', options: ['How old are you?', 'Where are you from?', 'What do you do?', 'Where do you live?'], correctIndex: 1, explanation: "¿De dónde eres? asks about someone's origin." },
        { type: 'word_match', pairs: [{ left: 'Me llamo', right: 'My name is' }, { left: 'Soy de', right: 'I am from' }, { left: 'Tengo _ años', right: 'I am _ years old' }, { left: 'Vivo en', right: 'I live in' }, { left: 'Soy estudiante', right: 'I am a student' }] },
        { type: 'fill_blank', sentence: 'Tengo veinticinco _____.', answer: 'años', hint: 'Word for years' },
      ]}),
      flashcards: [
        { front: '¿Cómo te llamas?', back: 'What is your name?', tags: 'introductions,questions' },
        { front: 'Me llamo...', back: 'My name is...', tags: 'introductions,phrases' },
        { front: '¿De dónde eres?', back: 'Where are you from?', tags: 'introductions,questions' },
        { front: 'Soy de...', back: 'I am from...', tags: 'introductions,phrases' },
        { front: '¿Cuántos años tienes?', back: 'How old are you?', tags: 'introductions,questions' },
        { front: 'Tengo ___ años', back: 'I am ___ years old', tags: 'introductions,age' },
        { front: 'Encantado/a', back: 'Pleased to meet you', tags: 'introductions,courtesy' },
        { front: 'Soy estudiante', back: 'I am a student', tags: 'introductions,professions' },
        { front: '¿Hablas español?', back: 'Do you speak Spanish?', tags: 'introductions,language' },
        { front: 'Un poco', back: 'A little', tags: 'basic,expressions' },
      ],
    },
    {
      id: 'lesson-1-3',
      title: 'Courtesy Expressions',
      description: 'Master please, thank you, sorry, and other polite phrases',
      level: 'A1', unit: 1, order: 3, type: 'VOCABULARY', estimatedMinutes: 8, xpReward: 25,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: "How do you say \"Excuse me\" to get someone's attention?", options: ['Lo siento', 'Perdón', 'De nada', 'Gracias'], correctIndex: 1, explanation: 'Perdón means "Excuse me" or "Sorry" for minor interruptions.' },
        { type: 'fill_blank', sentence: 'Lo _____, no entiendo.', answer: 'siento', hint: '"Lo siento" means "I\'m sorry"' },
        { type: 'word_match', pairs: [{ left: 'Por favor', right: 'Please' }, { left: 'Gracias', right: 'Thank you' }, { left: 'Lo siento', right: "I'm sorry" }, { left: 'Perdón', right: 'Excuse me' }, { left: 'Con mucho gusto', right: 'With pleasure' }] },
        { type: 'multiple_choice', question: 'What is the formal way to say "thank you very much"?', options: ['Gracias', 'Muchas gracias', 'De nada', 'Por favor'], correctIndex: 1, explanation: 'Muchas gracias means "Thank you very much".' },
        { type: 'fill_blank', sentence: '¿Puede repetir, _____?', answer: 'por favor', hint: 'Polite request word' },
        { type: 'sentence_builder', words: ['siento', 'Lo', 'mucho'], answer: 'Lo siento mucho', translation: 'I am very sorry' },
        { type: 'multiple_choice', question: 'Which phrase means "No problem"?', options: ['De nada', 'Sin problema', 'Lo siento', 'Perdón'], correctIndex: 1, explanation: 'Sin problema literally means "without a problem".' },
        { type: 'fill_blank', sentence: 'No hay _____, está bien.', answer: 'problema', hint: 'Word for problem' },
      ]}),
      flashcards: [
        { front: 'Por favor', back: 'Please', tags: 'courtesy,essential' },
        { front: 'Muchas gracias', back: 'Thank you very much', tags: 'courtesy,gratitude' },
        { front: 'Lo siento', back: "I'm sorry", tags: 'courtesy,apology' },
        { front: 'Perdón', back: 'Excuse me / Sorry', tags: 'courtesy,apology' },
        { front: 'Con mucho gusto', back: 'With pleasure', tags: 'courtesy,expressions' },
        { front: 'No hay problema', back: 'No problem', tags: 'courtesy,expressions' },
        { front: 'Disculpe', back: 'Excuse me (formal)', tags: 'courtesy,formal' },
        { front: '¿Puede repetir?', back: 'Can you repeat?', tags: 'courtesy,requests' },
        { front: 'No entiendo', back: "I don't understand", tags: 'basic,communication' },
        { front: '¿Cómo se dice...?', back: 'How do you say...?', tags: 'basic,communication' },
      ],
    },
    {
      id: 'lesson-1-4',
      title: 'Formal vs Informal Spanish',
      description: 'Learn when to use tú vs usted',
      level: 'A1', unit: 1, order: 4, type: 'GRAMMAR', estimatedMinutes: 10, xpReward: 30,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'Which pronoun is used formally in Spanish?', options: ['Tú', 'Usted', 'Vos', 'Él'], correctIndex: 1, explanation: 'Usted (Ud.) is the formal "you" used with elders, professionals, or strangers.' },
        { type: 'fill_blank', sentence: '_____ señor, ¿cómo se llama?', answer: 'Usted', hint: 'Formal "you" pronoun' },
        { type: 'multiple_choice', question: 'When would you use "tú"?', options: ['With your boss', 'With a stranger', 'With a friend your age', 'With an elder'], correctIndex: 2, explanation: 'Tú is the informal "you" used with friends, family, and peers.' },
        { type: 'word_match', pairs: [{ left: '¿Cómo estás?', right: 'How are you? (informal)' }, { left: '¿Cómo está usted?', right: 'How are you? (formal)' }, { left: '¿Cómo te llamas?', right: "What's your name? (informal)" }, { left: '¿Cómo se llama?', right: "What's your name? (formal)" }, { left: 'Hablas bien', right: 'You speak well (informal)' }] },
        { type: 'fill_blank', sentence: 'Doctor García, ¿cómo _____ usted?', answer: 'está', hint: 'Formal form of estar' },
        { type: 'multiple_choice', question: 'Which is appropriate when meeting your professor?', options: ['¿Cómo estás?', '¿Cómo está usted?', '¿Qué tal?', 'Oye, hola'], correctIndex: 1, explanation: 'Use formal usted with professors and authority figures.' },
        { type: 'fill_blank', sentence: 'María, ¿cómo _____ ? (informal)', answer: 'estás', hint: 'Informal form of estar for tú' },
        { type: 'sentence_builder', words: ['llama', 'usted', 'se', '¿Cómo'], answer: '¿Cómo se llama usted?', translation: 'What is your name? (formal)' },
      ]}),
      flashcards: [
        { front: 'Tú', back: 'You (informal)', tags: 'grammar,pronouns' },
        { front: 'Usted', back: 'You (formal)', tags: 'grammar,pronouns' },
        { front: '¿Cómo estás?', back: 'How are you? (informal)', tags: 'greetings,informal' },
        { front: '¿Cómo está usted?', back: 'How are you? (formal)', tags: 'greetings,formal' },
        { front: '¿Cómo te llamas?', back: "What's your name? (informal)", tags: 'questions,informal' },
        { front: '¿Cómo se llama?', back: "What's your name? (formal)", tags: 'questions,formal' },
        { front: 'Estoy bien', back: 'I am well', tags: 'responses,greetings' },
        { front: 'Muy bien, gracias', back: 'Very well, thank you', tags: 'responses,greetings' },
        { front: 'Más o menos', back: 'So-so / More or less', tags: 'responses,greetings' },
        { front: 'Regular', back: 'So-so / Average', tags: 'responses,greetings' },
      ],
    },
    {
      id: 'lesson-1-5',
      title: 'Goodbye & Farewell',
      description: 'Learn different ways to say goodbye in Spanish',
      level: 'A1', unit: 1, order: 5, type: 'VOCABULARY', estimatedMinutes: 8, xpReward: 25,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "Hasta mañana" mean?', options: ['See you later', 'See you tomorrow', 'Goodbye forever', 'Good night'], correctIndex: 1, explanation: 'Hasta mañana = Until tomorrow = See you tomorrow.' },
        { type: 'word_match', pairs: [{ left: 'Adiós', right: 'Goodbye' }, { left: 'Hasta luego', right: 'See you later' }, { left: 'Hasta mañana', right: 'See you tomorrow' }, { left: 'Hasta pronto', right: 'See you soon' }, { left: 'Nos vemos', right: "We'll see each other" }] },
        { type: 'fill_blank', sentence: '¡Hasta _____, amigo!', answer: 'luego', hint: '"Until later"' },
        { type: 'multiple_choice', question: 'Which is the most permanent goodbye?', options: ['Hasta luego', 'Hasta pronto', 'Adiós', 'Nos vemos'], correctIndex: 2, explanation: 'Adiós is the most definitive goodbye.' },
        { type: 'fill_blank', sentence: '¡Buenas _____, que descanses!', answer: 'noches', hint: 'Said when going to sleep' },
        { type: 'sentence_builder', words: ['pronto', 'Hasta'], answer: '¡Hasta pronto!', translation: 'See you soon!' },
        { type: 'multiple_choice', question: '"¡Que te vaya bien!" means:', options: ['Have a good day!', 'Take care!', 'I hope things go well for you!', 'Come back soon!'], correctIndex: 2, explanation: 'Que te vaya bien expresses good wishes when parting.' },
        { type: 'fill_blank', sentence: '¡_____ vemos mañana!', answer: 'Nos', hint: "We'll see each other" },
      ]}),
      flashcards: [
        { front: 'Adiós', back: 'Goodbye', tags: 'farewells,basic' },
        { front: 'Hasta luego', back: 'See you later', tags: 'farewells,common' },
        { front: 'Hasta mañana', back: 'See you tomorrow', tags: 'farewells,time' },
        { front: 'Hasta pronto', back: 'See you soon', tags: 'farewells,common' },
        { front: 'Nos vemos', back: "We'll see each other / See you", tags: 'farewells,colloquial' },
        { front: 'Cuídate', back: 'Take care of yourself', tags: 'farewells,care' },
        { front: 'Que te vaya bien', back: 'I hope things go well for you', tags: 'farewells,wishes' },
        { front: 'Chao', back: 'Bye (informal)', tags: 'farewells,informal' },
        { front: 'Buenas noches', back: 'Good night', tags: 'greetings,farewells' },
        { front: 'Que descanses', back: 'Rest well / Good night', tags: 'farewells,wishes' },
      ],
    },
    {
      id: 'lesson-2-1',
      title: 'Numbers 1–20',
      description: 'Count from one to twenty in Spanish',
      level: 'A1', unit: 2, order: 1, type: 'VOCABULARY', estimatedMinutes: 10, xpReward: 30,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'How do you say "five" in Spanish?', options: ['Cuatro', 'Seis', 'Cinco', 'Siete'], correctIndex: 2, explanation: 'Cinco = five' },
        { type: 'fill_blank', sentence: 'Tengo _____ hermanos. (3)', answer: 'tres', hint: 'Number three' },
        { type: 'word_match', pairs: [{ left: 'Uno', right: '1' }, { left: 'Cinco', right: '5' }, { left: 'Diez', right: '10' }, { left: 'Quince', right: '15' }, { left: 'Veinte', right: '20' }] },
        { type: 'multiple_choice', question: 'What number is "doce"?', options: ['11', '12', '13', '14'], correctIndex: 1, explanation: 'Doce = twelve' },
        { type: 'sentence_builder', words: ['tiene', 'años', 'dieciséis', 'Elena'], answer: 'Elena tiene dieciséis años', translation: 'Elena is sixteen years old' },
        { type: 'fill_blank', sentence: 'Hay _____ estudiantes en la clase. (20)', answer: 'veinte', hint: 'The number 20' },
        { type: 'multiple_choice', question: 'Which number comes after "nueve"?', options: ['Ocho', 'Diez', 'Once', 'Siete'], correctIndex: 1, explanation: 'Nueve = 9, Diez = 10' },
        { type: 'fill_blank', sentence: 'Son las _____ en punto. (8)', answer: 'ocho', hint: 'Number eight' },
      ]}),
      flashcards: [
        { front: 'Uno', back: 'One (1)', tags: 'numbers,basic' },
        { front: 'Dos', back: 'Two (2)', tags: 'numbers,basic' },
        { front: 'Tres', back: 'Three (3)', tags: 'numbers,basic' },
        { front: 'Cuatro', back: 'Four (4)', tags: 'numbers,basic' },
        { front: 'Cinco', back: 'Five (5)', tags: 'numbers,basic' },
        { front: 'Diez', back: 'Ten (10)', tags: 'numbers,basic' },
        { front: 'Once', back: 'Eleven (11)', tags: 'numbers,teens' },
        { front: 'Quince', back: 'Fifteen (15)', tags: 'numbers,teens' },
        { front: 'Dieciocho', back: 'Eighteen (18)', tags: 'numbers,teens' },
        { front: 'Veinte', back: 'Twenty (20)', tags: 'numbers,basic' },
      ],
    },
    {
      id: 'lesson-2-2',
      title: 'Telling Time',
      description: 'Learn to read and tell time in Spanish',
      level: 'A1', unit: 2, order: 2, type: 'GRAMMAR', estimatedMinutes: 12, xpReward: 30,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: "How do you say \"It is 3 o'clock\"?", options: ['Es la tres', 'Son las tres', 'Está las tres', 'Son los tres'], correctIndex: 1, explanation: 'Use "Son las" for all hours except 1 o\'clock.' },
        { type: 'fill_blank', sentence: '_____ la una en punto.', answer: 'Es', hint: 'Use "Es" only for 1 o\'clock' },
        { type: 'multiple_choice', question: 'What does "Son las cuatro y media" mean?', options: ["It's 4:15", "It's 4:30", "It's 4:45", "It's 4:00"], correctIndex: 1, explanation: '"Y media" means "and a half" = 30 minutes.' },
        { type: 'word_match', pairs: [{ left: 'y cuarto', right: 'quarter past / :15' }, { left: 'y media', right: 'half past / :30' }, { left: 'menos cuarto', right: 'quarter to / :45' }, { left: 'en punto', right: "o'clock / exactly" }, { left: 'de la mañana', right: 'in the morning / AM' }] },
        { type: 'fill_blank', sentence: 'Son las ocho _____ cuarto.', answer: 'y', hint: '"And" in time expressions' },
        { type: 'multiple_choice', question: '"Son las dos menos diez" means:', options: ["It's 1:50", "It's 2:10", "It's 2:50", "It's 1:10"], correctIndex: 0, explanation: 'Menos = minus. 2:00 minus 10 minutes = 1:50.' },
        { type: 'sentence_builder', words: ['las', 'Son', 'de', 'siete', 'noche', 'la'], answer: 'Son las siete de la noche', translation: "It's 7 PM" },
        { type: 'fill_blank', sentence: '¿A qué hora empieza la clase? A las _____.', answer: 'nueve', hint: "Nine o'clock" },
      ]}),
      flashcards: [
        { front: '¿Qué hora es?', back: 'What time is it?', tags: 'time,questions' },
        { front: 'Son las...', back: "It's... o'clock (plural)", tags: 'time,telling' },
        { front: 'Es la una', back: "It's one o'clock", tags: 'time,telling' },
        { front: 'y media', back: 'and a half / :30', tags: 'time,expressions' },
        { front: 'y cuarto', back: 'quarter past / :15', tags: 'time,expressions' },
        { front: 'menos cuarto', back: 'quarter to / :45', tags: 'time,expressions' },
        { front: 'de la mañana', back: 'in the morning / AM', tags: 'time,periods' },
        { front: 'de la tarde', back: 'in the afternoon / PM', tags: 'time,periods' },
        { front: 'de la noche', back: 'at night / PM (evening)', tags: 'time,periods' },
        { front: 'a mediodía', back: 'at noon', tags: 'time,periods' },
      ],
    },
    {
      id: 'lesson-2-3',
      title: 'Days of the Week',
      description: 'Learn the seven days and how to use them',
      level: 'A1', unit: 2, order: 3, type: 'VOCABULARY', estimatedMinutes: 10, xpReward: 25,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'Which day comes after "martes"?', options: ['Lunes', 'Miércoles', 'Jueves', 'Viernes'], correctIndex: 1, explanation: 'Martes = Tuesday; Miércoles = Wednesday' },
        { type: 'word_match', pairs: [{ left: 'Lunes', right: 'Monday' }, { left: 'Miércoles', right: 'Wednesday' }, { left: 'Viernes', right: 'Friday' }, { left: 'Sábado', right: 'Saturday' }, { left: 'Domingo', right: 'Sunday' }] },
        { type: 'fill_blank', sentence: 'Hoy es _____ y mañana es jueves. (Wednesday)', answer: 'miércoles', hint: 'The day before Thursday' },
        { type: 'multiple_choice', question: 'What does "el fin de semana" mean?', options: ['The beginning of the week', 'The weekend', 'The middle of the week', 'The weekday'], correctIndex: 1, explanation: 'Fin de semana = weekend (Saturday and Sunday).' },
        { type: 'fill_blank', sentence: 'La clase de español es los _____ (Tuesdays).', answer: 'martes', hint: 'Tuesday in Spanish' },
        { type: 'sentence_builder', words: ['clase', 'El', 'lunes', 'hay'], answer: 'El lunes hay clase', translation: 'On Monday there is class' },
        { type: 'multiple_choice', question: 'In Spanish calendars, the week starts on:', options: ['Sunday', 'Monday', 'Saturday', 'Tuesday'], correctIndex: 1, explanation: 'Spanish/European calendars start on Monday (lunes).' },
        { type: 'fill_blank', sentence: '¿Qué día es hoy? Hoy es _____.', answer: 'lunes', hint: 'The first day of the week' },
      ]}),
      flashcards: [
        { front: 'Lunes', back: 'Monday', tags: 'days,week' },
        { front: 'Martes', back: 'Tuesday', tags: 'days,week' },
        { front: 'Miércoles', back: 'Wednesday', tags: 'days,week' },
        { front: 'Jueves', back: 'Thursday', tags: 'days,week' },
        { front: 'Viernes', back: 'Friday', tags: 'days,week' },
        { front: 'Sábado', back: 'Saturday', tags: 'days,weekend' },
        { front: 'Domingo', back: 'Sunday', tags: 'days,weekend' },
        { front: 'El fin de semana', back: 'The weekend', tags: 'time,expressions' },
        { front: 'Hoy', back: 'Today', tags: 'time,basic' },
        { front: 'Mañana', back: 'Tomorrow', tags: 'time,basic' },
      ],
    },
    {
      id: 'lesson-3-1',
      title: 'Family Members',
      description: 'Learn vocabulary for family relationships',
      level: 'A1', unit: 3, order: 1, type: 'VOCABULARY', estimatedMinutes: 10, xpReward: 30,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "la madre" mean?', options: ['Sister', 'Daughter', 'Mother', 'Aunt'], correctIndex: 2, explanation: 'La madre = the mother' },
        { type: 'word_match', pairs: [{ left: 'El padre', right: 'Father' }, { left: 'La hermana', right: 'Sister' }, { left: 'El abuelo', right: 'Grandfather' }, { left: 'La tía', right: 'Aunt' }, { left: 'El primo', right: 'Cousin (male)' }] },
        { type: 'fill_blank', sentence: 'Tengo dos _____ (brothers) y una hermana.', answer: 'hermanos', hint: 'Plural of brother' },
        { type: 'multiple_choice', question: 'How do you say "my grandmother"?', options: ['Mi abuela', 'Mi abuelo', 'Mi madre', 'Mi tía'], correctIndex: 0, explanation: 'Abuela = grandmother (feminine)' },
        { type: 'sentence_builder', words: ['mi', 'son', 'padres', 'simpáticos', 'Mis'], answer: 'Mis padres son simpáticos', translation: 'My parents are nice' },
        { type: 'fill_blank', sentence: 'Mi _____ (husband) se llama Roberto.', answer: 'esposo', hint: 'Word for husband' },
        { type: 'multiple_choice', question: 'What is the plural of "hijo" (son)?', options: ['Hijas', 'Hijos', 'Hijitos', 'Hijotes'], correctIndex: 1, explanation: 'Hijo → Hijos in the plural.' },
        { type: 'fill_blank', sentence: 'La _____ de mi madre es mi tía.', answer: 'hermana', hint: 'Sister of your mother' },
      ]}),
      flashcards: [
        { front: 'La madre', back: 'Mother', tags: 'family,immediate' },
        { front: 'El padre', back: 'Father', tags: 'family,immediate' },
        { front: 'El hermano', back: 'Brother', tags: 'family,siblings' },
        { front: 'La hermana', back: 'Sister', tags: 'family,siblings' },
        { front: 'El abuelo', back: 'Grandfather', tags: 'family,extended' },
        { front: 'La abuela', back: 'Grandmother', tags: 'family,extended' },
        { front: 'El tío', back: 'Uncle', tags: 'family,extended' },
        { front: 'La tía', back: 'Aunt', tags: 'family,extended' },
        { front: 'El primo/La prima', back: 'Cousin', tags: 'family,extended' },
        { front: 'Los padres', back: 'Parents', tags: 'family,immediate' },
      ],
    },
    {
      id: 'lesson-4-1',
      title: 'Food & Drink Vocabulary',
      description: 'Essential vocabulary for ordering food and talking about meals',
      level: 'A2', unit: 4, order: 1, type: 'VOCABULARY', estimatedMinutes: 12, xpReward: 35,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "el desayuno" mean?', options: ['Lunch', 'Dinner', 'Breakfast', 'Snack'], correctIndex: 2, explanation: 'El desayuno = breakfast' },
        { type: 'word_match', pairs: [{ left: 'El pan', right: 'Bread' }, { left: 'La leche', right: 'Milk' }, { left: 'El agua', right: 'Water' }, { left: 'La carne', right: 'Meat' }, { left: 'Las verduras', right: 'Vegetables' }] },
        { type: 'fill_blank', sentence: 'Quiero un _____, por favor. (coffee)', answer: 'café', hint: 'Coffee without article' },
        { type: 'multiple_choice', question: 'Which word means "chicken"?', options: ['El cerdo', 'El pollo', 'El pescado', 'La ternera'], correctIndex: 1, explanation: 'El pollo = chicken' },
        { type: 'sentence_builder', words: ['la', 'ensalada', 'Quiero', 'favor', 'por'], answer: 'Quiero la ensalada por favor', translation: 'I want the salad please' },
        { type: 'fill_blank', sentence: 'El _____ (restaurant) está muy bueno.', answer: 'restaurante', hint: 'Place to eat out' },
        { type: 'multiple_choice', question: 'What does "tengo hambre" mean?', options: ["I'm thirsty", "I'm hungry", "I'm full", "I'm tired"], correctIndex: 1, explanation: 'Tener hambre = to be hungry' },
        { type: 'fill_blank', sentence: 'La cuenta, por _____ (please).', answer: 'favor', hint: 'Polite request word' },
      ]}),
      flashcards: [
        { front: 'El desayuno', back: 'Breakfast', tags: 'food,meals' },
        { front: 'El almuerzo', back: 'Lunch', tags: 'food,meals' },
        { front: 'La cena', back: 'Dinner', tags: 'food,meals' },
        { front: 'El pan', back: 'Bread', tags: 'food,staples' },
        { front: 'La leche', back: 'Milk', tags: 'food,drinks' },
        { front: 'El pollo', back: 'Chicken', tags: 'food,meat' },
        { front: 'Las verduras', back: 'Vegetables', tags: 'food,healthy' },
        { front: 'Tengo hambre', back: "I'm hungry", tags: 'food,expressions' },
        { front: 'Tengo sed', back: "I'm thirsty", tags: 'food,expressions' },
        { front: 'La cuenta', back: 'The bill/check', tags: 'restaurant,vocabulary' },
      ],
    },
    {
      id: 'lesson-5-1',
      title: 'Directions & Transportation',
      description: 'Navigate cities and use public transport in Spanish',
      level: 'A2', unit: 5, order: 1, type: 'VOCABULARY', estimatedMinutes: 12, xpReward: 35,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'How do you ask "Where is the station?"', options: ['¿Dónde está la estación?', '¿Cómo está la estación?', '¿Qué es la estación?', '¿Cuándo está la estación?'], correctIndex: 0, explanation: 'Use ¿Dónde está...? to ask where something is.' },
        { type: 'word_match', pairs: [{ left: 'A la derecha', right: 'To the right' }, { left: 'A la izquierda', right: 'To the left' }, { left: 'Todo recto', right: 'Straight ahead' }, { left: 'Doble aquí', right: 'Turn here' }, { left: 'El semáforo', right: 'The traffic light' }] },
        { type: 'fill_blank', sentence: 'Gire a la _____ en el semáforo.', answer: 'derecha', hint: 'Direction: right' },
        { type: 'multiple_choice', question: 'Which means "bus stop"?', options: ['La estación', 'La parada de autobús', 'El aeropuerto', 'El puerto'], correctIndex: 1, explanation: 'La parada = stop; El autobús = bus' },
        { type: 'sentence_builder', words: ['está', 'museo', '¿Dónde', 'el'], answer: '¿Dónde está el museo?', translation: 'Where is the museum?' },
        { type: 'fill_blank', sentence: 'El metro está a cinco _____ de aquí.', answer: 'minutos', hint: 'Unit of time' },
        { type: 'multiple_choice', question: 'What does "Está lejos" mean?', options: ["It's nearby", "It's far", "It's here", "It's there"], correctIndex: 1, explanation: 'Lejos = far; Cerca = near' },
        { type: 'fill_blank', sentence: 'Siga todo _____ por dos cuadras.', answer: 'recto', hint: 'Straight ahead' },
      ]}),
      flashcards: [
        { front: 'A la derecha', back: 'To the right', tags: 'directions,navigation' },
        { front: 'A la izquierda', back: 'To the left', tags: 'directions,navigation' },
        { front: 'Todo recto', back: 'Straight ahead', tags: 'directions,navigation' },
        { front: 'Cerca', back: 'Near/Close', tags: 'directions,distance' },
        { front: 'Lejos', back: 'Far', tags: 'directions,distance' },
        { front: '¿Dónde está...?', back: 'Where is...?', tags: 'directions,questions' },
        { front: 'La parada de autobús', back: 'Bus stop', tags: 'transport,public' },
        { front: 'El metro', back: 'Subway/Metro', tags: 'transport,public' },
        { front: 'El taxi', back: 'Taxi', tags: 'transport,vehicles' },
        { front: 'La estación de tren', back: 'Train station', tags: 'transport,places' },
      ],
    },
    {
      id: 'lesson-6-1',
      title: 'Work & Jobs',
      description: 'Vocabulary for professions and workplace situations',
      level: 'A2', unit: 6, order: 1, type: 'VOCABULARY', estimatedMinutes: 12, xpReward: 35,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "el médico" mean?', options: ['Mechanic', 'Doctor', 'Lawyer', 'Engineer'], correctIndex: 1, explanation: 'El médico/la médica = doctor' },
        { type: 'word_match', pairs: [{ left: 'El maestro', right: 'Teacher' }, { left: 'El abogado', right: 'Lawyer' }, { left: 'El ingeniero', right: 'Engineer' }, { left: 'El cocinero', right: 'Cook/Chef' }, { left: 'El enfermero', right: 'Nurse' }] },
        { type: 'fill_blank', sentence: 'Soy _____ (architect). Diseño edificios.', answer: 'arquitecto', hint: 'One who designs buildings' },
        { type: 'multiple_choice', question: 'How do you say "I work in an office"?', options: ['Trabajo en una escuela', 'Trabajo en una oficina', 'Trabajo en un hospital', 'Trabajo en una tienda'], correctIndex: 1, explanation: 'La oficina = office' },
        { type: 'sentence_builder', words: ['empresa', 'en', 'una', 'Trabajo', 'grande'], answer: 'Trabajo en una empresa grande', translation: 'I work in a large company' },
        { type: 'fill_blank', sentence: '¿A qué te _____? Soy programador.', answer: 'dedicas', hint: '"What do you do for a living?" verb' },
        { type: 'multiple_choice', question: 'What is "la empresa"?', options: ['Employment', 'Employee', 'Company/Business', 'Boss'], correctIndex: 2, explanation: 'La empresa = company, business' },
        { type: 'fill_blank', sentence: 'Mi jefe es muy _____ (demanding).', answer: 'exigente', hint: 'Adjective meaning demanding' },
      ]}),
      flashcards: [
        { front: 'El médico', back: 'Doctor', tags: 'professions,healthcare' },
        { front: 'El maestro/La maestra', back: 'Teacher', tags: 'professions,education' },
        { front: 'El abogado', back: 'Lawyer', tags: 'professions,law' },
        { front: 'El ingeniero', back: 'Engineer', tags: 'professions,technical' },
        { front: 'El arquitecto', back: 'Architect', tags: 'professions,technical' },
        { front: 'La empresa', back: 'Company/Business', tags: 'work,places' },
        { front: 'La oficina', back: 'Office', tags: 'work,places' },
        { front: 'El jefe/La jefa', back: 'Boss', tags: 'work,people' },
        { front: 'El sueldo', back: 'Salary', tags: 'work,money' },
        { front: 'Trabajar', back: 'To work', tags: 'work,verbs' },
      ],
    },
    {
      id: 'lesson-7-1',
      title: 'Health & Body Parts',
      description: 'Describe health issues and body parts in Spanish',
      level: 'B1', unit: 7, order: 1, type: 'VOCABULARY', estimatedMinutes: 15, xpReward: 40,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'How do you say "My head hurts"?', options: ['Mi cabeza duele', 'Me duele la cabeza', 'Tengo dolor cabeza', 'La cabeza me hace mal'], correctIndex: 1, explanation: 'Me duele + body part = the body part hurts me.' },
        { type: 'word_match', pairs: [{ left: 'La cabeza', right: 'Head' }, { left: 'El estómago', right: 'Stomach' }, { left: 'La garganta', right: 'Throat' }, { left: 'La espalda', right: 'Back' }, { left: 'El pecho', right: 'Chest' }] },
        { type: 'fill_blank', sentence: 'Me _____ la rodilla después de correr.', answer: 'duele', hint: 'Verb expressing pain' },
        { type: 'multiple_choice', question: 'How do you say "I have a fever"?', options: ['Tengo sed', 'Tengo fiebre', 'Tengo hambre', 'Tengo frío'], correctIndex: 1, explanation: 'Tener fiebre = to have a fever' },
        { type: 'fill_blank', sentence: 'El _____ me recetó medicamento.', answer: 'médico', hint: 'Person who treats illnesses' },
        { type: 'sentence_builder', words: ['me', 'mucho', 'duele', 'cabeza', 'La'], answer: 'La cabeza me duele mucho', translation: 'My head hurts a lot' },
        { type: 'multiple_choice', question: 'What does "estar resfriado" mean?', options: ['To be cold', 'To have a cold', 'To be feverish', 'To be tired'], correctIndex: 1, explanation: 'Estar resfriado/a = to have a cold' },
        { type: 'fill_blank', sentence: 'Necesito una _____ (appointment) con el dentista.', answer: 'cita', hint: 'Medical appointment' },
      ]}),
      flashcards: [
        { front: 'La cabeza', back: 'Head', tags: 'body,parts' },
        { front: 'El brazo', back: 'Arm', tags: 'body,parts' },
        { front: 'La pierna', back: 'Leg', tags: 'body,parts' },
        { front: 'El estómago', back: 'Stomach', tags: 'body,parts' },
        { front: 'Me duele', back: 'It hurts (me)', tags: 'health,expressions' },
        { front: 'Tengo fiebre', back: 'I have a fever', tags: 'health,symptoms' },
        { front: 'Estar resfriado/a', back: 'To have a cold', tags: 'health,illnesses' },
        { front: 'El médico', back: 'Doctor', tags: 'health,people' },
        { front: 'La farmacia', back: 'Pharmacy', tags: 'health,places' },
        { front: 'El medicamento', back: 'Medicine/Medication', tags: 'health,treatment' },
      ],
    },
    {
      id: 'lesson-8-1',
      title: 'Hobbies & Free Time',
      description: 'Talk about what you enjoy doing in your free time',
      level: 'B1', unit: 8, order: 1, type: 'SPEAKING', estimatedMinutes: 15, xpReward: 40,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "me gusta leer" mean?', options: ['I like to write', 'I like to read', 'I like to sing', 'I like to run'], correctIndex: 1, explanation: 'Leer = to read; Me gusta = I like' },
        { type: 'fill_blank', sentence: 'En mi tiempo libre, _____ (I enjoy) escuchar música.', answer: 'disfruto', hint: 'Verb meaning to enjoy' },
        { type: 'word_match', pairs: [{ left: 'Pintar', right: 'To paint' }, { left: 'Cocinar', right: 'To cook' }, { left: 'Bailar', right: 'To dance' }, { left: 'Jugar al fútbol', right: 'To play soccer' }, { left: 'Tocar la guitarra', right: 'To play guitar' }] },
        { type: 'multiple_choice', question: 'Which is stronger: "me gusta" or "me encanta"?', options: ['Me gusta is stronger', 'Me encanta is stronger', 'They are equal', 'Neither expresses liking'], correctIndex: 1, explanation: 'Me encanta = I love (stronger than me gusta = I like).' },
        { type: 'fill_blank', sentence: 'Me _____ mucho la música clásica.', answer: 'encanta', hint: 'Stronger form of liking' },
        { type: 'sentence_builder', words: ['libre', 'En', 'tiempo', 'mi', 'nado'], answer: 'En mi tiempo libre nado', translation: 'In my free time I swim' },
        { type: 'fill_blank', sentence: 'Mis _____ incluyen la lectura y el cine.', answer: 'aficiones', hint: 'Plural word for hobbies/interests' },
        { type: 'multiple_choice', question: 'What does "practicar deporte" mean?', options: ['To watch sports', 'To practice a sport / to exercise', 'To talk about sports', 'To coach a team'], correctIndex: 1, explanation: 'Practicar deporte = to exercise / to do sports.' },
      ]}),
      flashcards: [
        { front: 'El tiempo libre', back: 'Free time', tags: 'hobbies,expressions' },
        { front: 'Me gusta...', back: 'I like...', tags: 'hobbies,expressions' },
        { front: 'Me encanta...', back: 'I love...', tags: 'hobbies,expressions' },
        { front: 'Leer', back: 'To read', tags: 'hobbies,activities' },
        { front: 'Escuchar música', back: 'To listen to music', tags: 'hobbies,activities' },
        { front: 'Jugar al fútbol', back: 'To play soccer', tags: 'hobbies,sports' },
        { front: 'Tocar la guitarra', back: 'To play guitar', tags: 'hobbies,music' },
        { front: 'Pintar', back: 'To paint', tags: 'hobbies,arts' },
        { front: 'Cocinar', back: 'To cook', tags: 'hobbies,activities' },
        { front: 'Las aficiones', back: 'Hobbies/Interests', tags: 'hobbies,vocabulary' },
      ],
    },
    {
      id: 'lesson-9-1',
      title: 'Current Events & News',
      description: 'Discuss news topics and current events in Spanish',
      level: 'B2', unit: 9, order: 1, type: 'READING', estimatedMinutes: 20, xpReward: 50,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "las noticias" mean?', options: ['The newspapers', 'The news', 'The journalists', 'The reports'], correctIndex: 1, explanation: 'Las noticias = the news' },
        { type: 'word_match', pairs: [{ left: 'El medio ambiente', right: 'The environment' }, { left: 'Las emisiones', right: 'Emissions' }, { left: 'El calentamiento global', right: 'Global warming' }, { left: 'Las energías renovables', right: 'Renewable energies' }, { left: 'La sostenibilidad', right: 'Sustainability' }] },
        { type: 'fill_blank', sentence: 'El _____ climático es un problema global urgente.', answer: 'cambio', hint: 'Change' },
        { type: 'multiple_choice', question: 'What does "según los científicos" mean?', options: ['Despite scientists', 'According to scientists', 'Without scientists', 'Against scientists'], correctIndex: 1, explanation: 'Según = according to' },
        { type: 'fill_blank', sentence: 'Los _____ (scientists) advierten sobre las consecuencias.', answer: 'científicos', hint: 'People who do science' },
        { type: 'sentence_builder', words: ['cambio', 'El', 'climático', 'urgente', 'es'], answer: 'El cambio climático es urgente', translation: 'Climate change is urgent' },
        { type: 'fill_blank', sentence: 'Sin _____, los problemas continúan.', answer: 'embargo', hint: 'Part of "however" connector' },
        { type: 'multiple_choice', question: 'What does "se enfrenta al desafío" mean?', options: ['Avoids the challenge', 'Creates the challenge', 'Faces the challenge', 'Ignores the challenge'], correctIndex: 2, explanation: 'Enfrentarse = to face; el desafío = the challenge' },
      ]}),
      flashcards: [
        { front: 'El medio ambiente', back: 'The environment', tags: 'current-events,environment' },
        { front: 'El cambio climático', back: 'Climate change', tags: 'current-events,environment' },
        { front: 'Las noticias', back: 'The news', tags: 'current-events,media' },
        { front: 'El periódico', back: 'Newspaper', tags: 'current-events,media' },
        { front: 'Según', back: 'According to', tags: 'current-events,connectors' },
        { front: 'Sin embargo', back: 'However/Nevertheless', tags: 'connectors,discourse' },
        { front: 'Además', back: 'Furthermore/Also', tags: 'connectors,discourse' },
        { front: 'El gobierno', back: 'The government', tags: 'current-events,politics' },
        { front: 'La economía', back: 'The economy', tags: 'current-events,economics' },
        { front: 'La sostenibilidad', back: 'Sustainability', tags: 'current-events,environment' },
      ],
    },
    {
      id: 'lesson-10-1',
      title: 'Abstract Concepts & Debate',
      description: 'Discuss complex ideas and argue positions in Spanish',
      level: 'C1', unit: 10, order: 1, type: 'WRITING', estimatedMinutes: 25, xpReward: 60,
      content: JSON.stringify({ exercises: [
        { type: 'multiple_choice', question: 'What does "por un lado... por otro lado" express?', options: ['Time sequence', 'Contrasting two sides', 'Cause and effect', 'Examples'], correctIndex: 1, explanation: '"On one hand... on the other hand" — presents contrasting perspectives.' },
        { type: 'word_match', pairs: [{ left: 'Por un lado', right: 'On one hand' }, { left: 'Por otro lado', right: 'On the other hand' }, { left: 'Sin embargo', right: 'However' }, { left: 'Cabe destacar que', right: 'It is worth noting that' }, { left: 'En conclusión', right: 'In conclusion' }] },
        { type: 'fill_blank', sentence: 'A pesar de los avances, _____ persisten desafíos fundamentales.', answer: 'aún', hint: 'Word meaning still/yet' },
        { type: 'multiple_choice', question: 'Which is the most formal discourse connector?', options: ['Pero', 'Y también', 'No obstante', 'O sea'], correctIndex: 2, explanation: 'No obstante is a formal alternative to sin embargo (however).' },
        { type: 'fill_blank', sentence: 'Es _____ señalar que las consecuencias son complejas.', answer: 'importante', hint: 'Adjective meaning important' },
        { type: 'sentence_builder', words: ['argumenta', 'que', 'Se', 'la', 'tecnología', 'el', 'es', 'futuro'], answer: 'Se argumenta que la tecnología es el futuro', translation: 'It is argued that technology is the future' },
        { type: 'multiple_choice', question: 'What does "exacerbar" mean?', options: ['To improve', 'To worsen/intensify', 'To resolve', 'To ignore'], correctIndex: 1, explanation: 'Exacerbar = to worsen, to exacerbate' },
        { type: 'fill_blank', sentence: 'La _____ (inequality) es un tema central en el debate.', answer: 'desigualdad', hint: 'Word for inequality' },
      ]}),
      flashcards: [
        { front: 'Por un lado... por otro lado', back: 'On one hand... on the other hand', tags: 'discourse,connectors,C1' },
        { front: 'No obstante', back: 'Nevertheless/However (formal)', tags: 'discourse,connectors,C1' },
        { front: 'Cabe destacar', back: 'It is worth noting', tags: 'discourse,connectors,C1' },
        { front: 'En definitiva', back: 'In short/Ultimately', tags: 'discourse,connectors,C1' },
        { front: 'La desigualdad', back: 'Inequality', tags: 'abstract,society,C1' },
        { front: 'La sostenibilidad', back: 'Sustainability', tags: 'abstract,environment,C1' },
        { front: 'La globalización', back: 'Globalization', tags: 'abstract,economics,C1' },
        { front: 'Plantear', back: 'To raise (an issue)/To pose', tags: 'verbs,academic,C1' },
        { front: 'Exacerbar', back: 'To worsen/exacerbate', tags: 'verbs,academic,C1' },
        { front: 'La adaptabilidad', back: 'Adaptability', tags: 'abstract,skills,C1' },
      ],
    },
  ];

  for (const lessonData of lessons) {
    const { flashcards: flashcardData, ...lessonFields } = lessonData;
    await prisma.lesson.upsert({
      where: { id: lessonFields.id },
      update: lessonFields,
      create: lessonFields,
    });

    for (const fc of flashcardData) {
      const fcId = `fc-${lessonFields.id}-${fc.front.substring(0, 12).replace(/[^a-zA-Z0-9]/g, '-')}`;
      await prisma.flashcard.upsert({
        where: { id: fcId },
        update: { ...fc, lessonId: lessonFields.id, language: 'Spanish' },
        create: { id: fcId, ...fc, lessonId: lessonFields.id, language: 'Spanish' },
      });
    }
    console.log(`Seeded: ${lessonFields.title}`);
  }

  // Seed today's daily challenge
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  await prisma.dailyChallenge.upsert({
    where: { date: today },
    update: {},
    create: {
      date: today,
      type: 'VOCABULARY',
      xpReward: 60,
      content: JSON.stringify({
        title: 'Daily Vocabulary Challenge',
        description: 'Match 10 Spanish words with their English translations',
        pairs: [
          { spanish: 'la biblioteca', english: 'the library' },
          { spanish: 'el aeropuerto', english: 'the airport' },
          { spanish: 'la farmacia', english: 'the pharmacy' },
          { spanish: 'el mercado', english: 'the market' },
          { spanish: 'la panadería', english: 'the bakery' },
          { spanish: 'el hospital', english: 'the hospital' },
          { spanish: 'la escuela', english: 'the school' },
          { spanish: 'el restaurante', english: 'the restaurant' },
          { spanish: 'la tienda', english: 'the store/shop' },
          { spanish: 'el banco', english: 'the bank' },
        ],
      }),
    },
  });

  console.log('✅ Database seeding completed!');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
