import { PrismaClient, CEFRLevel, LessonType } from '@prisma/client';

const prisma = new PrismaClient();

const achievements = [
  { id: 'first-lesson', title: 'First Step', description: 'Complete your first lesson', icon: '🎯', xpReward: 50, condition: { type: 'lessons_completed', count: 1 } },
  { id: 'five-lessons', title: 'Getting Started', description: 'Complete 5 lessons', icon: '📚', xpReward: 100, condition: { type: 'lessons_completed', count: 5 } },
  { id: 'ten-lessons', title: 'Dedicated Learner', description: 'Complete 10 lessons', icon: '🏆', xpReward: 200, condition: { type: 'lessons_completed', count: 10 } },
  { id: 'fifty-lessons', title: 'Language Champion', description: 'Complete 50 lessons', icon: '👑', xpReward: 500, condition: { type: 'lessons_completed', count: 50 } },
  { id: 'streak-3', title: 'On a Roll', description: 'Maintain a 3-day streak', icon: '🔥', xpReward: 75, condition: { type: 'streak', days: 3 } },
  { id: 'streak-7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '⚡', xpReward: 150, condition: { type: 'streak', days: 7 } },
  { id: 'streak-30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '💎', xpReward: 500, condition: { type: 'streak', days: 30 } },
  { id: 'streak-100', title: 'Century Streak', description: 'Maintain a 100-day streak', icon: '🌟', xpReward: 2000, condition: { type: 'streak', days: 100 } },
  { id: 'xp-500', title: 'Explorer', description: 'Earn 500 XP', icon: '🗺️', xpReward: 50, condition: { type: 'xp', amount: 500 } },
  { id: 'xp-1500', title: 'Adventurer', description: 'Earn 1500 XP', icon: '⚔️', xpReward: 100, condition: { type: 'xp', amount: 1500 } },
  { id: 'xp-5000', title: 'Scholar', description: 'Earn 5000 XP', icon: '🎓', xpReward: 200, condition: { type: 'xp', amount: 5000 } },
  { id: 'xp-10000', title: 'Linguist', description: 'Earn 10000 XP', icon: '🧠', xpReward: 500, condition: { type: 'xp', amount: 10000 } },
  { id: 'first-flashcard', title: 'Memory Maker', description: 'Review your first flashcard', icon: '🃏', xpReward: 25, condition: { type: 'flashcards_reviewed', count: 1 } },
  { id: 'flashcards-100', title: 'Card Shark', description: 'Review 100 flashcards', icon: '🎴', xpReward: 150, condition: { type: 'flashcards_reviewed', count: 100 } },
  { id: 'flashcards-500', title: 'Memory Palace', description: 'Review 500 flashcards', icon: '🏛️', xpReward: 300, condition: { type: 'flashcards_reviewed', count: 500 } },
  { id: 'first-speaking', title: 'First Words', description: 'Complete your first speaking session', icon: '🗣️', xpReward: 75, condition: { type: 'speaking_sessions', count: 1 } },
  { id: 'speaking-10', title: 'Conversationalist', description: 'Complete 10 speaking sessions', icon: '💬', xpReward: 200, condition: { type: 'speaking_sessions', count: 10 } },
  { id: 'first-writing', title: 'Pensmith', description: 'Write your first journal entry', icon: '✍️', xpReward: 50, condition: { type: 'writing_entries', count: 1 } },
  { id: 'writing-10', title: 'Storyteller', description: 'Write 10 journal entries', icon: '📖', xpReward: 150, condition: { type: 'writing_entries', count: 10 } },
  { id: 'perfect-lesson', title: 'Perfectionist', description: 'Get a perfect score on a lesson', icon: '💯', xpReward: 100, condition: { type: 'perfect_lesson', count: 1 } },
  { id: 'perfect-5', title: 'Flawless', description: 'Get perfect scores on 5 lessons', icon: '✨', xpReward: 250, condition: { type: 'perfect_lesson', count: 5 } },
  { id: 'daily-challenge', title: 'Daily Grind', description: 'Complete your first daily challenge', icon: '📅', xpReward: 60, condition: { type: 'daily_challenges', count: 1 } },
  { id: 'daily-challenge-7', title: 'Challenge Accepted', description: 'Complete 7 daily challenges', icon: '🎯', xpReward: 200, condition: { type: 'daily_challenges', count: 7 } },
  { id: 'leaderboard-top10', title: 'Rising Star', description: 'Reach top 10 on the leaderboard', icon: '⭐', xpReward: 300, condition: { type: 'leaderboard_rank', rank: 10 } },
  { id: 'leaderboard-top3', title: 'Podium Finisher', description: 'Reach top 3 on the leaderboard', icon: '🥉', xpReward: 500, condition: { type: 'leaderboard_rank', rank: 3 } },
  { id: 'leaderboard-1', title: 'Champion', description: 'Reach #1 on the leaderboard', icon: '🥇', xpReward: 1000, condition: { type: 'leaderboard_rank', rank: 1 } },
  { id: 'night-owl', title: 'Night Owl', description: 'Study after midnight', icon: '🦉', xpReward: 50, condition: { type: 'study_time', hour: 0 } },
  { id: 'early-bird', title: 'Early Bird', description: 'Study before 7am', icon: '🐦', xpReward: 50, condition: { type: 'study_time', hour: 7 } },
  { id: 'weekend-warrior', title: 'Weekend Warrior', description: 'Study on both Saturday and Sunday', icon: '🏖️', xpReward: 100, condition: { type: 'weekend_study' } },
  { id: 'all-unit1', title: 'Unit 1 Complete', description: 'Complete all lessons in Unit 1', icon: '🎊', xpReward: 200, condition: { type: 'unit_complete', unit: 1 } },
];

const lessons = [
  // Unit 1: Greetings & Introductions (A1)
  {
    title: 'Basic Greetings',
    description: 'Learn essential Spanish greetings for any time of day',
    level: CEFRLevel.A1,
    unit: 1,
    order: 1,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 10,
    xpReward: 30,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you say "Good morning" in Spanish?',
          options: ['Buenas noches', 'Buenos días', 'Buenas tardes', 'Hasta luego'],
          correctIndex: 1,
          explanation: 'Buenos días is used in the morning (roughly until noon).',
        },
        {
          type: 'multiple_choice',
          question: 'What does "¿Cómo estás?" mean?',
          options: ['What is your name?', 'Where are you from?', 'How are you?', 'How old are you?'],
          correctIndex: 2,
          explanation: '¿Cómo estás? is the informal way to ask "How are you?"',
        },
        {
          type: 'fill_blank',
          sentence: 'Hola, me llamo María. _____ gusto.',
          answer: 'Mucho',
          hint: 'This phrase means "Nice to meet you"',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'Hola', right: 'Hello' },
            { left: 'Adiós', right: 'Goodbye' },
            { left: 'Por favor', right: 'Please' },
            { left: 'Gracias', right: 'Thank you' },
            { left: 'De nada', right: "You're welcome" },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'Which greeting is used in the evening?',
          options: ['Buenos días', 'Buenos tardes', 'Buenas noches', 'Buenas mañanas'],
          correctIndex: 2,
          explanation: 'Buenas noches is used in the evening and at night.',
        },
        {
          type: 'sentence_builder',
          words: ['¿', 'Cómo', 'te', 'llamas', '?'],
          answer: '¿Cómo te llamas?',
          translation: 'What is your name? (informal)',
        },
        {
          type: 'fill_blank',
          sentence: 'Buenos días. ¿_____ estás?',
          answer: 'Cómo',
          hint: 'Complete the greeting question',
        },
        {
          type: 'multiple_choice',
          question: 'How do you respond to "¿Cómo estás?" positively?',
          options: ['Muy mal', 'Más o menos', 'Muy bien, gracias', 'No sé'],
          correctIndex: 2,
          explanation: 'Muy bien, gracias means "Very well, thank you"',
        },
      ],
    },
    flashcards: [
      { front: 'Hola', back: 'Hello', language: 'Spanish', tags: ['greetings', 'basic'] },
      { front: 'Adiós', back: 'Goodbye', language: 'Spanish', tags: ['greetings', 'basic'] },
      { front: 'Buenos días', back: 'Good morning', language: 'Spanish', tags: ['greetings', 'time'] },
      { front: 'Buenas tardes', back: 'Good afternoon', language: 'Spanish', tags: ['greetings', 'time'] },
      { front: 'Buenas noches', back: 'Good evening / Good night', language: 'Spanish', tags: ['greetings', 'time'] },
      { front: '¿Cómo estás?', back: 'How are you? (informal)', language: 'Spanish', tags: ['greetings', 'questions'] },
      { front: 'Muy bien', back: 'Very well', language: 'Spanish', tags: ['responses', 'basic'] },
      { front: 'Mucho gusto', back: 'Nice to meet you', language: 'Spanish', tags: ['greetings', 'introductions'] },
      { front: 'Por favor', back: 'Please', language: 'Spanish', tags: ['courtesy', 'basic'] },
      { front: 'Gracias', back: 'Thank you', language: 'Spanish', tags: ['courtesy', 'basic'] },
    ],
  },
  {
    title: 'Introducing Yourself',
    description: 'Learn how to introduce yourself and share basic personal information',
    level: CEFRLevel.A1,
    unit: 1,
    order: 2,
    type: LessonType.SPEAKING,
    estimatedMinutes: 12,
    xpReward: 35,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you say "My name is Carlos" in Spanish?',
          options: ['Me llamo Carlos', 'Yo soy Carlos nombre', 'Mi nombre es Carlos llamo', 'Llamo me Carlos'],
          correctIndex: 0,
          explanation: 'Me llamo literally means "I call myself" and is the most natural way to say your name.',
        },
        {
          type: 'fill_blank',
          sentence: 'Hola, yo _____ de México.',
          answer: 'soy',
          hint: 'Use the verb "to be" for origin',
        },
        {
          type: 'sentence_builder',
          words: ['Me', 'llamo', 'Ana', 'y', 'tengo', 'veinte', 'años'],
          answer: 'Me llamo Ana y tengo veinte años',
          translation: 'My name is Ana and I am twenty years old',
        },
        {
          type: 'multiple_choice',
          question: 'How do you ask someone where they are from?',
          options: ['¿Cómo te llamas?', '¿De dónde eres?', '¿Cuántos años tienes?', '¿Dónde vives?'],
          correctIndex: 1,
          explanation: '¿De dónde eres? means "Where are you from?" (informal)',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'Me llamo', right: 'My name is' },
            { left: 'Tengo ... años', right: 'I am ... years old' },
            { left: 'Soy de', right: 'I am from' },
            { left: 'Vivo en', right: 'I live in' },
            { left: 'Soy estudiante', right: 'I am a student' },
          ],
        },
        {
          type: 'fill_blank',
          sentence: 'Mucho gusto. ¿Cómo _____ llamas?',
          answer: 'te',
          hint: 'Reflexive pronoun for informal "you"',
        },
        {
          type: 'multiple_choice',
          question: 'What does "Encantado/a" mean?',
          options: ['Nice to meet you', 'Goodbye', 'Excuse me', 'Thank you'],
          correctIndex: 0,
          explanation: 'Encantado (m) / Encantada (f) means "Delighted / Nice to meet you"',
        },
        {
          type: 'speaking_prompt',
          prompt: 'Introduce yourself in Spanish: say your name, where you are from, and how old you are.',
          sampleAnswer: 'Hola, me llamo [nombre]. Soy de [país]. Tengo [número] años.',
        },
      ],
    },
    flashcards: [
      { front: 'Me llamo...', back: 'My name is...', language: 'Spanish', tags: ['introductions', 'self'] },
      { front: 'Soy de...', back: 'I am from...', language: 'Spanish', tags: ['introductions', 'origin'] },
      { front: 'Tengo ... años', back: 'I am ... years old', language: 'Spanish', tags: ['introductions', 'age'] },
      { front: '¿De dónde eres?', back: 'Where are you from?', language: 'Spanish', tags: ['questions', 'origin'] },
      { front: '¿Cuántos años tienes?', back: 'How old are you?', language: 'Spanish', tags: ['questions', 'age'] },
      { front: 'Encantado/a', back: 'Pleased to meet you', language: 'Spanish', tags: ['introductions', 'courtesy'] },
      { front: 'Yo soy', back: 'I am', language: 'Spanish', tags: ['verbs', 'ser'] },
      { front: 'Vivo en', back: 'I live in', language: 'Spanish', tags: ['introductions', 'location'] },
      { front: 'Soy estudiante', back: 'I am a student', language: 'Spanish', tags: ['professions', 'introductions'] },
      { front: 'Habló español', back: 'I speak Spanish', language: 'Spanish', tags: ['languages', 'abilities'] },
    ],
  },
  {
    title: 'Formal vs Informal Address',
    description: 'Understand when to use tú vs usted and formal greetings',
    level: CEFRLevel.A1,
    unit: 1,
    order: 3,
    type: LessonType.GRAMMAR,
    estimatedMinutes: 15,
    xpReward: 40,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'Which pronoun is used formally with strangers or elders?',
          options: ['Tú', 'Vos', 'Usted', 'Él'],
          correctIndex: 2,
          explanation: 'Usted (abbreviated Ud.) is the formal "you" used with strangers, elders, and in professional settings.',
        },
        {
          type: 'multiple_choice',
          question: 'How do you formally ask "How are you?"',
          options: ['¿Cómo estás?', '¿Cómo está usted?', '¿Cómo te va?', '¿Qué tal?'],
          correctIndex: 1,
          explanation: '¿Cómo está usted? uses the formal "usted" form of estar.',
        },
        {
          type: 'fill_blank',
          sentence: 'Buenos días, señor García. ¿Cómo _____ usted?',
          answer: 'está',
          hint: 'Formal form of estar',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'Tú', right: 'Informal you' },
            { left: 'Usted', right: 'Formal you' },
            { left: 'Señor', right: 'Mr.' },
            { left: 'Señora', right: 'Mrs.' },
            { left: 'Señorita', right: 'Miss' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'In a job interview, which would you use?',
          options: ['Tú', 'Usted', 'Vosotros', 'Either one'],
          correctIndex: 1,
          explanation: 'In professional settings like job interviews, always use usted to show respect.',
        },
        {
          type: 'fill_blank',
          sentence: 'Hola María, ¿cómo _____ va? (informal)',
          answer: 'te',
          hint: 'Informal reflexive pronoun',
        },
        {
          type: 'multiple_choice',
          question: 'What is the correct formal response to "¿Cómo está usted?"',
          options: ['Muy bien, gracias. ¿Y tú?', 'Bien, gracias. ¿Y usted?', 'Bien. ¿Y tú?', 'Más o menos, ¿y tú?'],
          correctIndex: 1,
          explanation: 'When someone addresses you formally, you should respond formally too.',
        },
        {
          type: 'sentence_builder',
          words: ['Mucho', 'gusto', 'en', 'conocerle', 'señor'],
          answer: 'Mucho gusto en conocerle señor',
          translation: 'Very pleased to meet you, sir (formal)',
        },
      ],
    },
    flashcards: [
      { front: 'Tú', back: 'You (informal)', language: 'Spanish', tags: ['pronouns', 'grammar'] },
      { front: 'Usted (Ud.)', back: 'You (formal)', language: 'Spanish', tags: ['pronouns', 'grammar', 'formal'] },
      { front: 'Señor', back: 'Mr. / Sir', language: 'Spanish', tags: ['titles', 'formal'] },
      { front: 'Señora', back: 'Mrs. / Madam', language: 'Spanish', tags: ['titles', 'formal'] },
      { front: 'Señorita', back: 'Miss', language: 'Spanish', tags: ['titles', 'formal'] },
      { front: '¿Cómo está usted?', back: 'How are you? (formal)', language: 'Spanish', tags: ['greetings', 'formal'] },
      { front: 'Con permiso', back: 'Excuse me (to pass)', language: 'Spanish', tags: ['courtesy', 'formal'] },
      { front: 'Perdón / Perdone', back: 'Excuse me / I am sorry', language: 'Spanish', tags: ['courtesy', 'apologies'] },
      { front: 'Le presento a...', back: 'Allow me to introduce... (formal)', language: 'Spanish', tags: ['introductions', 'formal'] },
      { front: 'Un placer', back: 'A pleasure', language: 'Spanish', tags: ['greetings', 'formal'] },
    ],
  },
  {
    title: 'Common Expressions',
    description: 'Master everyday expressions and small talk phrases',
    level: CEFRLevel.A1,
    unit: 1,
    order: 4,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 10,
    xpReward: 30,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'What does "¡Claro que sí!" mean?',
          options: ['Of course not!', 'Of course!', 'I don\'t know!', 'Maybe!'],
          correctIndex: 1,
          explanation: 'Claro que sí means "Of course!" or "Certainly!"',
        },
        {
          type: 'word_match',
          pairs: [
            { left: '¡Claro!', right: 'Of course!' },
            { left: 'Tal vez', right: 'Maybe' },
            { left: 'Por supuesto', right: 'Of course / Certainly' },
            { left: 'No sé', right: "I don't know" },
            { left: '¡Qué bien!', right: 'How great!' },
          ],
        },
        {
          type: 'fill_blank',
          sentence: '¡_____ pena! No puedo ir contigo.',
          answer: 'Qué',
          hint: 'Expression of sympathy/regret',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "I don\'t understand" in Spanish?',
          options: ['No hablo', 'No entiendo', 'No puedo', 'No quiero'],
          correctIndex: 1,
          explanation: 'No entiendo means "I don\'t understand". You can also say "No comprendo".',
        },
        {
          type: 'sentence_builder',
          words: ['¿', 'Puede', 'repetir', 'más', 'despacio', '?'],
          answer: '¿Puede repetir más despacio?',
          translation: 'Can you repeat more slowly? (formal)',
        },
        {
          type: 'fill_blank',
          sentence: '¿Habla usted _____? Sólo un poco.',
          answer: 'inglés',
          hint: 'The language spoken in England',
        },
        {
          type: 'multiple_choice',
          question: 'What does "¿Cuánto cuesta?" mean?',
          options: ['Where is it?', 'What time is it?', 'How much does it cost?', 'Can I have it?'],
          correctIndex: 2,
          explanation: '¿Cuánto cuesta? is an essential shopping phrase.',
        },
        {
          type: 'multiple_choice',
          question: 'Which phrase means "See you later"?',
          options: ['Hasta mañana', 'Hasta luego', 'Hasta la vista', 'Nos vemos mañana'],
          correctIndex: 1,
          explanation: 'Hasta luego literally means "Until later" and is a common farewell.',
        },
      ],
    },
    flashcards: [
      { front: '¡Claro!', back: 'Of course!', language: 'Spanish', tags: ['expressions', 'agreement'] },
      { front: 'Tal vez / Quizás', back: 'Maybe / Perhaps', language: 'Spanish', tags: ['expressions', 'uncertainty'] },
      { front: 'No entiendo', back: "I don't understand", language: 'Spanish', tags: ['expressions', 'communication'] },
      { front: '¿Puede repetir?', back: 'Can you repeat?', language: 'Spanish', tags: ['expressions', 'communication'] },
      { front: 'Más despacio', back: 'More slowly', language: 'Spanish', tags: ['expressions', 'communication'] },
      { front: 'Hasta luego', back: 'See you later', language: 'Spanish', tags: ['farewells', 'basic'] },
      { front: 'Hasta mañana', back: 'See you tomorrow', language: 'Spanish', tags: ['farewells', 'time'] },
      { front: '¡Qué bien!', back: 'How great!', language: 'Spanish', tags: ['expressions', 'emotions'] },
      { front: '¡Qué pena!', back: 'What a shame!', language: 'Spanish', tags: ['expressions', 'emotions'] },
      { front: '¿Cómo se dice...?', back: 'How do you say...?', language: 'Spanish', tags: ['expressions', 'learning'] },
    ],
  },
  {
    title: 'Cultural Greetings',
    description: 'Learn about Hispanic greeting customs and cultural nuances',
    level: CEFRLevel.A1,
    unit: 1,
    order: 5,
    type: LessonType.READING,
    estimatedMinutes: 12,
    xpReward: 35,
    content: {
      exercises: [
        {
          type: 'reading_passage',
          title: 'Saludos en el Mundo Hispanohablante',
          text: 'En los países hispanohablantes, los saludos son muy importantes. En España y Latinoamérica, es común dar un beso en la mejilla cuando te presentan a alguien. Los hombres a veces se dan la mano o se abrazan si son amigos. En México, es común decir "¿Qué onda?" entre jóvenes amigos, mientras que en Argentina se dice "¿Cómo andás?" En España, la gente dice "¿Qué pasa?" o "¿Qué hay?" de manera informal.',
          questions: [
            {
              question: 'What physical greeting is common in Spanish-speaking countries?',
              options: ['A bow', 'A kiss on the cheek', 'A high five', 'A wave'],
              correctIndex: 1,
            },
            {
              question: 'What does "¿Qué onda?" mean in Mexican slang?',
              options: ['How is the wave?', "What's up?", 'Where are you going?', 'What happened?'],
              correctIndex: 1,
            },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'In Argentina, how do young people informally say "How are you?"',
          options: ['¿Cómo estás?', '¿Qué onda?', '¿Cómo andás?', '¿Qué pasa?'],
          correctIndex: 2,
          explanation: '¿Cómo andás? is characteristic of the Rioplatense Spanish spoken in Argentina.',
        },
        {
          type: 'fill_blank',
          sentence: 'En España, la gente dice "¿Qué _____?" de manera informal.',
          answer: 'pasa',
          hint: 'From the verb pasar (to happen)',
        },
        {
          type: 'word_match',
          pairs: [
            { left: '¿Qué onda?', right: 'Mexico' },
            { left: '¿Cómo andás?', right: 'Argentina' },
            { left: '¿Qué pasa?', right: 'Spain' },
            { left: '¿Qué hay?', right: 'Spain (casual)' },
            { left: 'Buen día', right: 'Argentina (formal)' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'When meeting someone for the first time in Latin America, what is most appropriate?',
          options: ['Only wave', 'Give two kisses', 'Give a kiss on the cheek', 'Bow slightly'],
          correctIndex: 2,
          explanation: 'One kiss on the right cheek is typical when being introduced, though customs vary by country.',
        },
        {
          type: 'fill_blank',
          sentence: 'Los hombres se dan la _____ cuando se saludan formalmente.',
          answer: 'mano',
          hint: 'Part of the body used in a handshake',
        },
        {
          type: 'multiple_choice',
          question: 'What is "el abrazo" in English?',
          options: ['A kiss', 'A hug', 'A handshake', 'A bow'],
          correctIndex: 1,
          explanation: 'El abrazo means "the hug" - common between male friends in Latin America.',
        },
        {
          type: 'multiple_choice',
          question: 'When should you use a formal greeting in Spanish?',
          options: ['With close friends', 'With children', 'With employers or elderly people', 'With siblings'],
          correctIndex: 2,
          explanation: 'Formal greetings using usted are appropriate with authority figures, employers, and elders.',
        },
      ],
    },
    flashcards: [
      { front: '¿Qué onda?', back: "What's up? (Mexican slang)", language: 'Spanish', tags: ['slang', 'mexico', 'greetings'] },
      { front: '¿Cómo andás?', back: 'How are you going? (Argentine)', language: 'Spanish', tags: ['slang', 'argentina', 'greetings'] },
      { front: '¿Qué pasa?', back: "What's happening? (Spanish slang)", language: 'Spanish', tags: ['slang', 'spain', 'greetings'] },
      { front: 'El beso en la mejilla', back: 'The kiss on the cheek', language: 'Spanish', tags: ['culture', 'greetings'] },
      { front: 'El abrazo', back: 'The hug', language: 'Spanish', tags: ['culture', 'greetings'] },
      { front: 'La mano', back: 'The hand', language: 'Spanish', tags: ['body', 'basic'] },
      { front: 'La mejilla', back: 'The cheek', language: 'Spanish', tags: ['body', 'face'] },
      { front: '¡Bienvenido/a!', back: 'Welcome!', language: 'Spanish', tags: ['greetings', 'hospitality'] },
      { front: 'El saludo', back: 'The greeting', language: 'Spanish', tags: ['culture', 'vocabulary'] },
      { front: 'Presentarse', back: 'To introduce oneself', language: 'Spanish', tags: ['verbs', 'introductions'] },
    ],
  },
  // Unit 2: Numbers & Time (A1)
  {
    title: 'Numbers 1-100',
    description: 'Learn to count and use numbers in everyday situations',
    level: CEFRLevel.A1,
    unit: 2,
    order: 6,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 12,
    xpReward: 30,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you say "fifteen" in Spanish?',
          options: ['Cinco', 'Quince', 'Cincuenta', 'Diez y seis'],
          correctIndex: 1,
          explanation: 'Quince is 15 in Spanish.',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'Uno', right: '1' },
            { left: 'Cinco', right: '5' },
            { left: 'Diez', right: '10' },
            { left: 'Veinte', right: '20' },
            { left: 'Cien', right: '100' },
          ],
        },
        {
          type: 'fill_blank',
          sentence: 'Hay _____ estudiantes en la clase. (There are 30 students)',
          answer: 'treinta',
          hint: 'The number 30 in Spanish',
        },
        {
          type: 'multiple_choice',
          question: 'What is "cuarenta y dos" in numbers?',
          options: ['24', '42', '402', '14'],
          correctIndex: 1,
          explanation: 'Cuarenta (40) + y (and) + dos (2) = 42',
        },
        {
          type: 'sentence_builder',
          words: ['Tengo', 'cincuenta', 'y', 'tres', 'años'],
          answer: 'Tengo cincuenta y tres años',
          translation: 'I am fifty-three years old',
        },
        {
          type: 'fill_blank',
          sentence: 'El autobús número _____ va al centro. (The number 75 bus)',
          answer: 'setenta y cinco',
          hint: '70 + 5',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "ninety-nine" in Spanish?',
          options: ['Noventa y nueve', 'Nueve y noventa', 'Noventa nueve', 'Nueve nueve'],
          correctIndex: 0,
          explanation: 'In Spanish, compound numbers use "y" (and): noventa y nueve.',
        },
        {
          type: 'multiple_choice',
          question: 'What number is "ochenta"?',
          options: ['18', '80', '8', '800'],
          correctIndex: 1,
          explanation: 'Ochenta is 80. Note: ocho is 8.',
        },
      ],
    },
    flashcards: [
      { front: 'Uno / Una', back: 'One', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Diez', back: 'Ten', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Veinte', back: 'Twenty', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Treinta', back: 'Thirty', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Cuarenta', back: 'Forty', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Cincuenta', back: 'Fifty', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Sesenta', back: 'Sixty', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Setenta', back: 'Seventy', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Ochenta', back: 'Eighty', language: 'Spanish', tags: ['numbers', 'basic'] },
      { front: 'Noventa', back: 'Ninety', language: 'Spanish', tags: ['numbers', 'basic'] },
    ],
  },
  {
    title: 'Telling Time',
    description: 'Learn how to ask and tell the time in Spanish',
    level: CEFRLevel.A1,
    unit: 2,
    order: 7,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 15,
    xpReward: 35,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you ask "What time is it?" in Spanish?',
          options: ['¿Qué hora eres?', '¿Cuándo es la hora?', '¿Qué hora es?', '¿La hora qué es?'],
          correctIndex: 2,
          explanation: '¿Qué hora es? is the standard way to ask for the time.',
        },
        {
          type: 'fill_blank',
          sentence: '_____ las tres de la tarde.',
          answer: 'Son',
          hint: 'Use "es" for 1 o\'clock, "son" for all other times',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "It is 1:00 o\'clock"?',
          options: ['Son las una', 'Es la una', 'Es las uno', 'Son la una'],
          correctIndex: 1,
          explanation: 'For 1 o\'clock, use "Es la una" (singular). For all other times, use "Son las..."',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'y cuarto', right: 'quarter past' },
            { left: 'y media', right: 'half past' },
            { left: 'menos cuarto', right: 'quarter to' },
            { left: 'en punto', right: "o'clock exactly" },
            { left: 'de la mañana', right: 'in the morning' },
          ],
        },
        {
          type: 'fill_blank',
          sentence: 'La reunión es a las dos _____ cuarto. (2:15)',
          answer: 'y',
          hint: 'Connecting word for minutes past the hour',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "It is 9:30 PM"?',
          options: ['Es las nueve y media de la noche', 'Son las nueve y media de la noche', 'Son la nueve y media de la tarde', 'Es nueve y treinta de la noche'],
          correctIndex: 1,
          explanation: 'Son las nueve y media de la noche - use "son" for 9, "y media" for :30.',
        },
        {
          type: 'sentence_builder',
          words: ['El', 'tren', 'sale', 'a', 'las', 'ocho', 'menos', 'diez'],
          answer: 'El tren sale a las ocho menos diez',
          translation: 'The train leaves at ten to eight (7:50)',
        },
        {
          type: 'fill_blank',
          sentence: 'El banco abre a las nueve de la _____.',
          answer: 'mañana',
          hint: 'The part of the day when the sun rises',
        },
      ],
    },
    flashcards: [
      { front: '¿Qué hora es?', back: 'What time is it?', language: 'Spanish', tags: ['time', 'questions'] },
      { front: 'Son las...', back: 'It is... (time)', language: 'Spanish', tags: ['time', 'expressions'] },
      { front: 'Es la una', back: 'It is one o\'clock', language: 'Spanish', tags: ['time', 'expressions'] },
      { front: 'y cuarto', back: 'quarter past', language: 'Spanish', tags: ['time', 'fractions'] },
      { front: 'y media', back: 'half past', language: 'Spanish', tags: ['time', 'fractions'] },
      { front: 'menos cuarto', back: 'quarter to', language: 'Spanish', tags: ['time', 'fractions'] },
      { front: 'de la mañana', back: 'in the morning / AM', language: 'Spanish', tags: ['time', 'parts of day'] },
      { front: 'de la tarde', back: 'in the afternoon / PM', language: 'Spanish', tags: ['time', 'parts of day'] },
      { front: 'de la noche', back: 'at night / PM', language: 'Spanish', tags: ['time', 'parts of day'] },
      { front: 'en punto', back: "exactly / o'clock", language: 'Spanish', tags: ['time', 'precision'] },
    ],
  },
  {
    title: 'Days and Months',
    description: 'Learn the days of the week and months of the year',
    level: CEFRLevel.A1,
    unit: 2,
    order: 8,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 12,
    xpReward: 30,
    content: {
      exercises: [
        {
          type: 'word_match',
          pairs: [
            { left: 'Lunes', right: 'Monday' },
            { left: 'Miércoles', right: 'Wednesday' },
            { left: 'Viernes', right: 'Friday' },
            { left: 'Domingo', right: 'Sunday' },
            { left: 'Sábado', right: 'Saturday' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'What is the first month of the year in Spanish?',
          options: ['Febrero', 'Enero', 'Marzo', 'Junio'],
          correctIndex: 1,
          explanation: 'Enero is January, the first month.',
        },
        {
          type: 'fill_blank',
          sentence: 'Mi cumpleaños es el quince de _____. (My birthday is March 15)',
          answer: 'marzo',
          hint: 'The third month of the year',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "On Tuesdays" in Spanish?',
          options: ['En martes', 'Los martes', 'El martes', 'Por martes'],
          correctIndex: 1,
          explanation: 'Use "los" + day of week to indicate recurring days: Los martes = On Tuesdays.',
        },
        {
          type: 'sentence_builder',
          words: ['Hoy', 'es', 'jueves', '21', 'de', 'agosto'],
          answer: 'Hoy es jueves 21 de agosto',
          translation: 'Today is Thursday, August 21st',
        },
        {
          type: 'fill_blank',
          sentence: 'La Navidad es el veinticinco de _____.',
          answer: 'diciembre',
          hint: 'The last month of the year',
        },
        {
          type: 'multiple_choice',
          question: 'In Spanish, which day is typically the first day of the week on calendars?',
          options: ['Domingo', 'Sábado', 'Lunes', 'Martes'],
          correctIndex: 2,
          explanation: 'In Spain and most of Latin America, the week starts on Monday (Lunes).',
        },
        {
          type: 'multiple_choice',
          question: 'What is "octubre" in English?',
          options: ['August', 'September', 'October', 'November'],
          correctIndex: 2,
          explanation: 'Octubre = October. Note that Spanish months are not capitalized.',
        },
      ],
    },
    flashcards: [
      { front: 'Lunes', back: 'Monday', language: 'Spanish', tags: ['days', 'time'] },
      { front: 'Martes', back: 'Tuesday', language: 'Spanish', tags: ['days', 'time'] },
      { front: 'Miércoles', back: 'Wednesday', language: 'Spanish', tags: ['days', 'time'] },
      { front: 'Jueves', back: 'Thursday', language: 'Spanish', tags: ['days', 'time'] },
      { front: 'Viernes', back: 'Friday', language: 'Spanish', tags: ['days', 'time'] },
      { front: 'Sábado', back: 'Saturday', language: 'Spanish', tags: ['days', 'weekend'] },
      { front: 'Domingo', back: 'Sunday', language: 'Spanish', tags: ['days', 'weekend'] },
      { front: 'Enero', back: 'January', language: 'Spanish', tags: ['months', 'time'] },
      { front: 'Julio', back: 'July', language: 'Spanish', tags: ['months', 'time'] },
      { front: 'Diciembre', back: 'December', language: 'Spanish', tags: ['months', 'time'] },
    ],
  },
  {
    title: 'Dates and Seasons',
    description: 'Talk about dates, seasons, and weather',
    level: CEFRLevel.A1,
    unit: 2,
    order: 9,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 12,
    xpReward: 30,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you say "spring" in Spanish?',
          options: ['El verano', 'El otoño', 'La primavera', 'El invierno'],
          correctIndex: 2,
          explanation: 'La primavera is spring.',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'La primavera', right: 'Spring' },
            { left: 'El verano', right: 'Summer' },
            { left: 'El otoño', right: 'Autumn/Fall' },
            { left: 'El invierno', right: 'Winter' },
            { left: 'El tiempo', right: 'The weather' },
          ],
        },
        {
          type: 'fill_blank',
          sentence: '¿Qué tiempo _____ hoy? Hace mucho frío.',
          answer: 'hace',
          hint: 'Verb used for weather expressions',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "It is raining" in Spanish?',
          options: ['Hace lluvia', 'Está lloviendo', 'Es lluvioso', 'Llueve mucho hoy'],
          correctIndex: 1,
          explanation: 'Está lloviendo uses the present progressive. "Llueve" (it rains) is also correct.',
        },
        {
          type: 'sentence_builder',
          words: ['Hoy', 'hace', 'sol', 'y', 'no', 'hace', 'frío'],
          answer: 'Hoy hace sol y no hace frío',
          translation: 'Today it is sunny and not cold',
        },
        {
          type: 'fill_blank',
          sentence: 'En el invierno hace mucho _____ en Canadá.',
          answer: 'frío',
          hint: 'The opposite of hot',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "the date" in Spanish?',
          options: ['El tiempo', 'La cita', 'La fecha', 'El día'],
          correctIndex: 2,
          explanation: 'La fecha means "the date" (calendar). La cita is a date/appointment with a person.',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "It is 25 degrees" in Spanish?',
          options: ['Hace veinticinco grados', 'Son veinticinco grados', 'Es veinticinco grados', 'Hay veinticinco grados'],
          correctIndex: 0,
          explanation: 'Use "hace" + temperature: Hace veinticinco grados.',
        },
      ],
    },
    flashcards: [
      { front: 'La primavera', back: 'Spring', language: 'Spanish', tags: ['seasons', 'nature'] },
      { front: 'El verano', back: 'Summer', language: 'Spanish', tags: ['seasons', 'nature'] },
      { front: 'El otoño', back: 'Autumn / Fall', language: 'Spanish', tags: ['seasons', 'nature'] },
      { front: 'El invierno', back: 'Winter', language: 'Spanish', tags: ['seasons', 'nature'] },
      { front: 'Hace calor', back: 'It is hot', language: 'Spanish', tags: ['weather', 'expressions'] },
      { front: 'Hace frío', back: 'It is cold', language: 'Spanish', tags: ['weather', 'expressions'] },
      { front: 'Llueve / Está lloviendo', back: 'It rains / It is raining', language: 'Spanish', tags: ['weather', 'verbs'] },
      { front: 'Hace sol', back: 'It is sunny', language: 'Spanish', tags: ['weather', 'expressions'] },
      { front: 'La fecha', back: 'The date', language: 'Spanish', tags: ['time', 'vocabulary'] },
      { front: 'Hoy es...', back: 'Today is...', language: 'Spanish', tags: ['time', 'expressions'] },
    ],
  },
  {
    title: 'Numbers in Context',
    description: 'Use numbers for prices, phone numbers, and addresses',
    level: CEFRLevel.A1,
    unit: 2,
    order: 10,
    type: LessonType.GRAMMAR,
    estimatedMinutes: 15,
    xpReward: 40,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you say "The book costs twelve euros"?',
          options: ['El libro cuesta doce euros', 'El libro está doce euros', 'El libro tiene doce euros', 'El libro vale de doce euros'],
          correctIndex: 0,
          explanation: 'Costar (to cost) is the correct verb for prices.',
        },
        {
          type: 'fill_blank',
          sentence: 'Mi número de teléfono es _____ - treinta y dos - cuarenta y cinco. (555)',
          answer: 'cinco cinco cinco',
          hint: 'Phone numbers are usually said digit by digit or in pairs',
        },
        {
          type: 'word_match',
          pairs: [
            { left: '€2.50', right: 'Dos euros con cincuenta' },
            { left: '$100', right: 'Cien dólares' },
            { left: '1st floor', right: 'El primer piso' },
            { left: 'Apt 3B', right: 'Apartamento tres B' },
            { left: '1,000', right: 'Mil' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'How do you say 1,000 in Spanish?',
          options: ['Un millón', 'Cien', 'Mil', 'Ciento'],
          correctIndex: 2,
          explanation: 'Mil = 1,000. Millón = 1,000,000.',
        },
        {
          type: 'sentence_builder',
          words: ['Vivo', 'en', 'la', 'calle', 'Mayor,', 'número', 'quince'],
          answer: 'Vivo en la calle Mayor, número quince',
          translation: 'I live on Main Street, number 15',
        },
        {
          type: 'fill_blank',
          sentence: 'Somos _____ personas en total. (We are 5 people total)',
          answer: 'cinco',
          hint: 'The number 5',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "half a kilo" in Spanish?',
          options: ['Medio kilo', 'La mitad kilo', 'Cincuenta gramos', 'Un medio kilo'],
          correctIndex: 0,
          explanation: 'Medio/a means "half" and is used before nouns: medio kilo, media hora.',
        },
        {
          type: 'multiple_choice',
          question: 'What does "el segundo piso" mean?',
          options: ['The first floor', 'The second floor', 'The ground floor', 'The basement'],
          correctIndex: 1,
          explanation: 'El segundo piso = the second floor. Note: in Spain, "planta baja" is the ground floor.',
        },
      ],
    },
    flashcards: [
      { front: 'Mil', back: '1,000 (one thousand)', language: 'Spanish', tags: ['numbers', 'large'] },
      { front: 'Un millón', back: '1,000,000 (one million)', language: 'Spanish', tags: ['numbers', 'large'] },
      { front: '¿Cuánto cuesta?', back: 'How much does it cost?', language: 'Spanish', tags: ['shopping', 'questions'] },
      { front: 'Cuesta... euros', back: 'It costs... euros', language: 'Spanish', tags: ['shopping', 'prices'] },
      { front: 'Medio/a', back: 'Half', language: 'Spanish', tags: ['numbers', 'fractions'] },
      { front: 'El primer piso', back: 'The first floor', language: 'Spanish', tags: ['ordinals', 'location'] },
      { front: 'El segundo piso', back: 'The second floor', language: 'Spanish', tags: ['ordinals', 'location'] },
      { front: 'El número de teléfono', back: 'The phone number', language: 'Spanish', tags: ['vocabulary', 'technology'] },
      { front: 'La dirección', back: 'The address', language: 'Spanish', tags: ['vocabulary', 'location'] },
      { front: 'El precio', back: 'The price', language: 'Spanish', tags: ['shopping', 'vocabulary'] },
    ],
  },
  // Unit 3: Family & People (A1)
  {
    title: 'Family Members',
    description: 'Learn vocabulary for family relationships',
    level: CEFRLevel.A1,
    unit: 3,
    order: 11,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 12,
    xpReward: 30,
    content: {
      exercises: [
        {
          type: 'word_match',
          pairs: [
            { left: 'La madre', right: 'Mother' },
            { left: 'El padre', right: 'Father' },
            { left: 'El hermano', right: 'Brother' },
            { left: 'La hermana', right: 'Sister' },
            { left: 'Los abuelos', right: 'Grandparents' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'What is "el sobrino" in English?',
          options: ['Uncle', 'Nephew', 'Cousin', 'Brother-in-law'],
          correctIndex: 1,
          explanation: 'El sobrino = nephew, la sobrina = niece.',
        },
        {
          type: 'fill_blank',
          sentence: 'Mi _____ tiene ochenta años y vive con nosotros. (My grandmother)',
          answer: 'abuela',
          hint: 'Female grandparent',
        },
        {
          type: 'sentence_builder',
          words: ['Tengo', 'dos', 'hermanos', 'y', 'una', 'hermana'],
          answer: 'Tengo dos hermanos y una hermana',
          translation: 'I have two brothers and one sister',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "my parents" in Spanish?',
          options: ['Mis parientes', 'Mis padres', 'Mis papás', 'Mis madres'],
          correctIndex: 1,
          explanation: 'Mis padres means "my parents". Parientes means "relatives".',
        },
        {
          type: 'fill_blank',
          sentence: 'El hijo de mi tío es mi _____.',
          answer: 'primo',
          hint: 'Your uncle\'s son is your...',
        },
        {
          type: 'multiple_choice',
          question: 'What does "los suegros" mean?',
          options: ['Siblings', 'In-laws (parents)', 'Cousins', 'Grandchildren'],
          correctIndex: 1,
          explanation: 'Los suegros = in-laws (your spouse\'s parents). El suegro = father-in-law.',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "only child" in Spanish?',
          options: ['El único niño', 'Hijo único', 'Solo hijo', 'El niño solo'],
          correctIndex: 1,
          explanation: 'Hijo único (m) / Hija única (f) = only child.',
        },
      ],
    },
    flashcards: [
      { front: 'La madre / La mamá', back: 'Mother / Mom', language: 'Spanish', tags: ['family', 'basic'] },
      { front: 'El padre / El papá', back: 'Father / Dad', language: 'Spanish', tags: ['family', 'basic'] },
      { front: 'El hermano / La hermana', back: 'Brother / Sister', language: 'Spanish', tags: ['family', 'siblings'] },
      { front: 'El abuelo / La abuela', back: 'Grandfather / Grandmother', language: 'Spanish', tags: ['family', 'elders'] },
      { front: 'El hijo / La hija', back: 'Son / Daughter', language: 'Spanish', tags: ['family', 'children'] },
      { front: 'El tío / La tía', back: 'Uncle / Aunt', language: 'Spanish', tags: ['family', 'extended'] },
      { front: 'El primo / La prima', back: 'Male cousin / Female cousin', language: 'Spanish', tags: ['family', 'extended'] },
      { front: 'El sobrino / La sobrina', back: 'Nephew / Niece', language: 'Spanish', tags: ['family', 'extended'] },
      { front: 'El suegro / La suegra', back: 'Father-in-law / Mother-in-law', language: 'Spanish', tags: ['family', 'in-laws'] },
      { front: 'Los parientes', back: 'Relatives', language: 'Spanish', tags: ['family', 'general'] },
    ],
  },
  // Unit 4: Food & Restaurants (A2)
  {
    title: 'Food Vocabulary',
    description: 'Learn the names of common foods and drinks in Spanish',
    level: CEFRLevel.A2,
    unit: 4,
    order: 16,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 12,
    xpReward: 35,
    content: {
      exercises: [
        {
          type: 'word_match',
          pairs: [
            { left: 'El pan', right: 'Bread' },
            { left: 'La leche', right: 'Milk' },
            { left: 'El huevo', right: 'Egg' },
            { left: 'La carne', right: 'Meat' },
            { left: 'Las verduras', right: 'Vegetables' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'What is "el desayuno"?',
          options: ['Lunch', 'Dinner', 'Breakfast', 'Snack'],
          correctIndex: 2,
          explanation: 'El desayuno = breakfast. El almuerzo = lunch. La cena = dinner.',
        },
        {
          type: 'fill_blank',
          sentence: 'Me gusta mucho el _____ con leche por la mañana. (coffee)',
          answer: 'café',
          hint: 'Hot morning drink',
        },
        {
          type: 'sentence_builder',
          words: ['¿', 'Qué', 'desea', 'usted', 'de', 'beber', '?'],
          answer: '¿Qué desea usted de beber?',
          translation: 'What would you like to drink? (formal)',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "I am hungry" in Spanish?',
          options: ['Estoy hambre', 'Tengo hambre', 'Soy hambriento', 'Me gusta comer'],
          correctIndex: 1,
          explanation: 'Tener hambre (to have hunger) - Tengo hambre = I am hungry.',
        },
        {
          type: 'fill_blank',
          sentence: 'Para el postre, quiero _____ de chocolate. (cake)',
          answer: 'pastel',
          hint: 'A sweet baked dessert',
        },
        {
          type: 'multiple_choice',
          question: 'What does "sin gluten" mean on a menu?',
          options: ['Without sugar', 'Without gluten', 'Low fat', 'Extra spicy'],
          correctIndex: 1,
          explanation: 'Sin = without. Sin gluten = gluten-free.',
        },
        {
          type: 'multiple_choice',
          question: 'Which meal is "la cena"?',
          options: ['Breakfast', 'Lunch', 'Dinner', 'Snack'],
          correctIndex: 2,
          explanation: 'La cena is dinner, typically eaten later in the evening in Spanish-speaking countries.',
        },
      ],
    },
    flashcards: [
      { front: 'El desayuno', back: 'Breakfast', language: 'Spanish', tags: ['food', 'meals'] },
      { front: 'El almuerzo', back: 'Lunch', language: 'Spanish', tags: ['food', 'meals'] },
      { front: 'La cena', back: 'Dinner', language: 'Spanish', tags: ['food', 'meals'] },
      { front: 'El pan', back: 'Bread', language: 'Spanish', tags: ['food', 'staples'] },
      { front: 'La carne', back: 'Meat', language: 'Spanish', tags: ['food', 'proteins'] },
      { front: 'El pescado', back: 'Fish', language: 'Spanish', tags: ['food', 'proteins'] },
      { front: 'Las verduras', back: 'Vegetables', language: 'Spanish', tags: ['food', 'healthy'] },
      { front: 'La fruta', back: 'Fruit', language: 'Spanish', tags: ['food', 'healthy'] },
      { front: 'Tengo hambre', back: 'I am hungry', language: 'Spanish', tags: ['food', 'expressions'] },
      { front: 'Tengo sed', back: 'I am thirsty', language: 'Spanish', tags: ['food', 'expressions'] },
    ],
  },
  // Unit 5: Travel & Directions (A2)
  {
    title: 'Getting Around',
    description: 'Learn how to ask for and give directions in Spanish',
    level: CEFRLevel.A2,
    unit: 5,
    order: 22,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 15,
    xpReward: 40,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'How do you ask "Where is the train station?" in Spanish?',
          options: ['¿Dónde está la estación de tren?', '¿Cuándo es la estación de tren?', '¿Cómo se va a la estación?', '¿La estación dónde está?'],
          correctIndex: 0,
          explanation: '¿Dónde está...? = Where is...? Use estar for location.',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'Gire a la derecha', right: 'Turn right' },
            { left: 'Gire a la izquierda', right: 'Turn left' },
            { left: 'Siga todo recto', right: 'Go straight ahead' },
            { left: 'Cruce la calle', right: 'Cross the street' },
            { left: 'En la esquina', right: 'On the corner' },
          ],
        },
        {
          type: 'fill_blank',
          sentence: 'El museo está a dos cuadras de _____.',
          answer: 'aquí',
          hint: 'Word meaning "here"',
        },
        {
          type: 'sentence_builder',
          words: ['Tome', 'la', 'primera', 'calle', 'a', 'la', 'derecha'],
          answer: 'Tome la primera calle a la derecha',
          translation: 'Take the first street on the right',
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "How far is it?" in Spanish?',
          options: ['¿Cómo está de lejos?', '¿Cuánto lejos es?', '¿A qué distancia está?', '¿Qué tan lejos es?'],
          correctIndex: 2,
          explanation: '¿A qué distancia está? is the most formal way. ¿Qué tan lejos está? is also used in Latin America.',
        },
        {
          type: 'fill_blank',
          sentence: 'El hotel está _____ el supermercado y la farmacia.',
          answer: 'entre',
          hint: 'Position word meaning "between"',
        },
        {
          type: 'multiple_choice',
          question: 'What does "el semáforo" mean?',
          options: ['The crosswalk', 'The traffic light', 'The stop sign', 'The roundabout'],
          correctIndex: 1,
          explanation: 'El semáforo = the traffic light.',
        },
        {
          type: 'multiple_choice',
          question: 'How do you politely ask a stranger for directions?',
          options: ['¡Oye! ¿Dónde está el banco?', 'Perdone, ¿podría decirme dónde está el banco?', '¿Sabes dónde está el banco?', 'El banco, ¿dónde?'],
          correctIndex: 1,
          explanation: 'Perdone + ¿podría...? is a polite way to ask strangers for help.',
        },
      ],
    },
    flashcards: [
      { front: '¿Dónde está...?', back: 'Where is...?', language: 'Spanish', tags: ['directions', 'questions'] },
      { front: 'A la derecha', back: 'To the right', language: 'Spanish', tags: ['directions', 'basic'] },
      { front: 'A la izquierda', back: 'To the left', language: 'Spanish', tags: ['directions', 'basic'] },
      { front: 'Todo recto / derecho', back: 'Straight ahead', language: 'Spanish', tags: ['directions', 'basic'] },
      { front: 'La esquina', back: 'The corner', language: 'Spanish', tags: ['directions', 'places'] },
      { front: 'La cuadra / El bloque', back: 'The city block', language: 'Spanish', tags: ['directions', 'distance'] },
      { front: 'El semáforo', back: 'The traffic light', language: 'Spanish', tags: ['directions', 'city'] },
      { front: 'El cruce / La intersección', back: 'The intersection / crossroads', language: 'Spanish', tags: ['directions', 'city'] },
      { front: 'Cerca de', back: 'Near / Close to', language: 'Spanish', tags: ['directions', 'proximity'] },
      { front: 'Lejos de', back: 'Far from', language: 'Spanish', tags: ['directions', 'distance'] },
    ],
  },
  // Unit 7: Health & Body (B1)
  {
    title: 'The Human Body',
    description: 'Learn body parts and how to describe physical ailments',
    level: CEFRLevel.B1,
    unit: 7,
    order: 34,
    type: LessonType.VOCABULARY,
    estimatedMinutes: 15,
    xpReward: 45,
    content: {
      exercises: [
        {
          type: 'word_match',
          pairs: [
            { left: 'La cabeza', right: 'Head' },
            { left: 'El hombro', right: 'Shoulder' },
            { left: 'El pecho', right: 'Chest' },
            { left: 'La rodilla', right: 'Knee' },
            { left: 'El tobillo', right: 'Ankle' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'How do you say "I have a headache" in Spanish?',
          options: ['Tengo dolor de cabeza', 'Mi cabeza duele mucho', 'Estoy dolorido de cabeza', 'Me duele la cabeza'],
          correctIndex: 3,
          explanation: 'Me duele la cabeza (My head hurts) is the most natural expression. Both this and "Tengo dolor de cabeza" are correct.',
        },
        {
          type: 'fill_blank',
          sentence: 'Me duele el _____ cuando corro mucho. (My knee hurts)',
          answer: 'rodilla',
          hint: 'The joint in the middle of your leg',
        },
        {
          type: 'sentence_builder',
          words: ['Desde', 'ayer', 'tengo', 'fiebre', 'y', 'tos'],
          answer: 'Desde ayer tengo fiebre y tos',
          translation: 'Since yesterday I have had a fever and a cough',
        },
        {
          type: 'multiple_choice',
          question: 'At the doctor\'s office, how do you say "I have been feeling sick for three days"?',
          options: ['Me siento mal por tres días', 'Llevo tres días sintiéndome mal', 'Tengo tres días de estar mal', 'Hace tres días que me siento mal'],
          correctIndex: 1,
          explanation: '"Llevar + tiempo + gerundio" is a common structure: Llevo tres días sintiéndome mal.',
        },
        {
          type: 'fill_blank',
          sentence: 'El médico me recetó un _____ para la infección. (antibiotic)',
          answer: 'antibiótico',
          hint: 'Medicine that fights bacterial infections',
        },
        {
          type: 'multiple_choice',
          question: 'What does "estar resfriado" mean?',
          options: ['To be cold (temperature)', 'To have a cold', 'To feel refreshed', 'To be frozen'],
          correctIndex: 1,
          explanation: 'Estar resfriado/a = to have a cold.',
        },
        {
          type: 'multiple_choice',
          question: 'How do you tell a doctor your symptoms in Spanish?',
          options: ['Mis síntomas son', 'Me encuentro que...', 'Tengo los siguientes síntomas:', 'Both A and C'],
          correctIndex: 3,
          explanation: 'Both "Mis síntomas son" and "Tengo los siguientes síntomas" are correct ways to describe symptoms.',
        },
      ],
    },
    flashcards: [
      { front: 'Me duele...', back: '...hurts (my ... hurts)', language: 'Spanish', tags: ['health', 'pain'] },
      { front: 'La cabeza', back: 'Head', language: 'Spanish', tags: ['body', 'health'] },
      { front: 'El estómago', back: 'Stomach', language: 'Spanish', tags: ['body', 'health'] },
      { front: 'La fiebre', back: 'Fever', language: 'Spanish', tags: ['health', 'symptoms'] },
      { front: 'La tos', back: 'Cough', language: 'Spanish', tags: ['health', 'symptoms'] },
      { front: 'Estar resfriado/a', back: 'To have a cold', language: 'Spanish', tags: ['health', 'illness'] },
      { front: 'El médico / La médica', back: 'The doctor', language: 'Spanish', tags: ['health', 'people'] },
      { front: 'La receta', back: 'The prescription', language: 'Spanish', tags: ['health', 'medical'] },
      { front: 'El antibiótico', back: 'Antibiotic', language: 'Spanish', tags: ['health', 'medicine'] },
      { front: 'Llevo ... días...', back: 'I have been ... for ... days', language: 'Spanish', tags: ['health', 'time expressions'] },
    ],
  },
  // Unit 9: News & Current Events (B2)
  {
    title: 'Reading the News',
    description: 'Understand news articles and discuss current events in Spanish',
    level: CEFRLevel.B2,
    unit: 9,
    order: 49,
    type: LessonType.READING,
    estimatedMinutes: 20,
    xpReward: 55,
    content: {
      exercises: [
        {
          type: 'reading_passage',
          title: 'El Cambio Climático: Un Desafío Global',
          text: 'El cambio climático se ha convertido en uno de los mayores desafíos que enfrenta la humanidad en el siglo XXI. Según los últimos informes del Panel Intergubernamental sobre el Cambio Climático (IPCC), la temperatura global ha aumentado 1.1 grados centígrados desde la era preindustrial. Los científicos advierten que si no se toman medidas urgentes, las consecuencias podrían ser devastadoras: el aumento del nivel del mar, fenómenos meteorológicos extremos y la extinción de numerosas especies.\n\nLos países latinoamericanos son especialmente vulnerables a estos cambios. La Amazonía, considerada el "pulmón del planeta", está siendo deforestada a un ritmo alarmante. Sin embargo, varios países de la región han comenzado a implementar políticas de energías renovables y reforestación para combatir este fenómeno.',
          questions: [
            {
              question: 'According to the IPCC, how much has global temperature increased?',
              options: ['0.5 degrees', '1.1 degrees', '2.0 degrees', '1.5 degrees'],
              correctIndex: 1,
            },
            {
              question: 'What is the Amazon rainforest called in the passage?',
              options: ['The green lung', 'The planet\'s lung', 'The world\'s forest', 'The last frontier'],
              correctIndex: 1,
            },
          ],
        },
        {
          type: 'vocabulary_in_context',
          sentence: 'Los científicos advierten que las consecuencias podrían ser devastadoras.',
          word: 'advierten',
          options: ['celebrate', 'warn', 'discover', 'ignore'],
          correctIndex: 1,
        },
        {
          type: 'fill_blank',
          sentence: 'La _____ de bosques es una de las principales causas del cambio climático.',
          answer: 'deforestación',
          hint: 'The removal of forests',
        },
        {
          type: 'multiple_choice',
          question: 'What does "fenómenos meteorológicos extremos" refer to?',
          options: ['Moderate weather', 'Extreme weather events', 'Seasonal changes', 'Climate predictions'],
          correctIndex: 1,
          explanation: 'Fenómenos meteorológicos extremos = extreme weather phenomena/events.',
        },
        {
          type: 'sentence_builder',
          words: ['El', 'gobierno', 'ha', 'implementado', 'nuevas', 'políticas', 'medioambientales'],
          answer: 'El gobierno ha implementado nuevas políticas medioambientales',
          translation: 'The government has implemented new environmental policies',
        },
        {
          type: 'fill_blank',
          sentence: 'Según los _____, la situación es más grave de lo que pensábamos.',
          answer: 'expertos',
          hint: 'People with specialized knowledge',
        },
        {
          type: 'multiple_choice',
          question: 'In news Spanish, what does "se espera que" mean?',
          options: ['It is expected that', 'It is hoped that', 'It is feared that', 'It is known that'],
          correctIndex: 0,
          explanation: '"Se espera que" = "It is expected that" - common in journalistic writing.',
        },
        {
          type: 'writing_prompt',
          prompt: 'Write 3-4 sentences in Spanish summarizing the main points of the article about climate change.',
          sampleAnswer: 'El cambio climático es un problema global serio. La temperatura ha aumentado 1.1 grados desde la era preindustrial. La Amazonía está siendo deforestada rápidamente. Varios países están implementando políticas de energías renovables.',
        },
      ],
    },
    flashcards: [
      { front: 'El cambio climático', back: 'Climate change', language: 'Spanish', tags: ['environment', 'current events'] },
      { front: 'La deforestación', back: 'Deforestation', language: 'Spanish', tags: ['environment', 'problems'] },
      { front: 'Las energías renovables', back: 'Renewable energies', language: 'Spanish', tags: ['environment', 'solutions'] },
      { front: 'El nivel del mar', back: 'Sea level', language: 'Spanish', tags: ['environment', 'geography'] },
      { front: 'Según los expertos', back: 'According to experts', language: 'Spanish', tags: ['news', 'expressions'] },
      { front: 'Se ha convertido en', back: 'Has become', language: 'Spanish', tags: ['grammar', 'perfect tense'] },
      { front: 'Sin embargo', back: 'However / Nevertheless', language: 'Spanish', tags: ['connectors', 'writing'] },
      { front: 'A un ritmo alarmante', back: 'At an alarming rate', language: 'Spanish', tags: ['expressions', 'news'] },
      { front: 'Implementar políticas', back: 'To implement policies', language: 'Spanish', tags: ['politics', 'verbs'] },
      { front: 'El desafío', back: 'The challenge', language: 'Spanish', tags: ['vocabulary', 'problems'] },
    ],
  },
  // Unit 10: Abstract Ideas & Debate (C1)
  {
    title: 'Expressing Opinions and Debating',
    description: 'Master advanced structures for argumentation and expressing nuanced opinions',
    level: CEFRLevel.C1,
    unit: 10,
    order: 57,
    type: LessonType.WRITING,
    estimatedMinutes: 25,
    xpReward: 65,
    content: {
      exercises: [
        {
          type: 'multiple_choice',
          question: 'Which phrase is most appropriate for formally introducing your opinion?',
          options: ['Yo pienso que...', 'A mi entender / A mi modo de ver...', 'Para mí...', 'Creo que...'],
          correctIndex: 1,
          explanation: '"A mi entender" / "A mi modo de ver" are more sophisticated and appropriate in formal debates.',
        },
        {
          type: 'fill_blank',
          sentence: '_____ los argumentos presentados, es evidente que la situación requiere una solución urgente.',
          answer: 'Habida cuenta de',
          hint: 'A formal phrase meaning "given/considering"',
        },
        {
          type: 'word_match',
          pairs: [
            { left: 'Sin embargo', right: 'However' },
            { left: 'No obstante', right: 'Nevertheless' },
            { left: 'A pesar de que', right: 'Despite the fact that' },
            { left: 'Cabe destacar que', right: 'It is worth noting that' },
            { left: 'En suma', right: 'In sum / To summarize' },
          ],
        },
        {
          type: 'multiple_choice',
          question: 'When countering an argument formally in Spanish, which is most effective?',
          options: [
            'Eso no es verdad porque...',
            'Si bien es cierto que..., no hay que olvidar que...',
            'Pero eso está mal porque...',
            'No, no, yo no creo eso.',
          ],
          correctIndex: 1,
          explanation: '"Si bien es cierto que... no hay que olvidar que..." acknowledges the opposing view while countering it gracefully.',
        },
        {
          type: 'sentence_builder',
          words: ['Cabe', 'señalar', 'que', 'los', 'datos', 'respaldan', 'esta', 'teoría'],
          answer: 'Cabe señalar que los datos respaldan esta teoría',
          translation: 'It is worth pointing out that the data supports this theory',
        },
        {
          type: 'writing_prompt',
          prompt: 'Write a short argumentative paragraph (5-6 sentences) in Spanish arguing for or against social media regulation. Use at least 3 discourse markers.',
          sampleAnswer: 'A mi modo de ver, la regulación de las redes sociales es no solo conveniente sino imprescindible en la sociedad actual. Si bien es cierto que la libertad de expresión es un derecho fundamental, no hay que olvidar que el anonimato en línea facilita la propagación de desinformación y discurso de odio. Cabe destacar que varios países europeos ya han implementado marcos regulatorios efectivos sin comprometer la libertad de sus ciudadanos. En suma, una regulación equilibrada beneficiaría a toda la sociedad.',
        },
        {
          type: 'fill_blank',
          sentence: 'Los _____ demuestran que la inversión en educación tiene un impacto positivo a largo plazo.',
          answer: 'datos',
          hint: 'Factual information used to support arguments',
        },
        {
          type: 'multiple_choice',
          question: 'What is the subjunctive used for in formal debate language?',
          options: [
            'Only for past events',
            'For doubt, emotion, and hypothetical situations',
            'Only for future events',
            'It is not used in debates',
          ],
          correctIndex: 1,
          explanation: 'The subjunctive expresses doubt, uncertainty, emotion, and hypothetical scenarios - all common in debate.',
        },
      ],
    },
    flashcards: [
      { front: 'A mi entender / A mi modo de ver', back: 'In my view / As I see it', language: 'Spanish', tags: ['opinions', 'formal', 'discourse'] },
      { front: 'Si bien es cierto que...', back: 'While it is true that...', language: 'Spanish', tags: ['concession', 'debate', 'discourse'] },
      { front: 'No obstante', back: 'Nevertheless / However', language: 'Spanish', tags: ['connectors', 'contrast'] },
      { front: 'Cabe destacar que', back: 'It is worth highlighting that', language: 'Spanish', tags: ['emphasis', 'formal'] },
      { front: 'En suma / En resumen', back: 'In sum / In summary', language: 'Spanish', tags: ['connectors', 'conclusion'] },
      { front: 'Los datos respaldan', back: 'The data supports', language: 'Spanish', tags: ['argumentation', 'evidence'] },
      { front: 'Habida cuenta de', back: 'Given / Taking into account', language: 'Spanish', tags: ['formal', 'connectors'] },
      { front: 'El argumento', back: 'The argument', language: 'Spanish', tags: ['debate', 'vocabulary'] },
      { front: 'Refutar', back: 'To refute / To counter', language: 'Spanish', tags: ['debate', 'verbs'] },
      { front: 'La desinformación', back: 'Misinformation / Disinformation', language: 'Spanish', tags: ['media', 'current events'] },
    ],
  },
];

async function main() {
  console.log('Seeding database...');

  // Seed achievements
  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { id: achievement.id },
      update: achievement,
      create: achievement,
    });
  }
  console.log(`Seeded ${achievements.length} achievements`);

  // Seed lessons and flashcards
  for (const lessonData of lessons) {
    const { flashcards: flashcardData, content, ...lessonFields } = lessonData;

    const lesson = await prisma.lesson.upsert({
      where: { id: `seed-lesson-${lessonFields.unit}-${lessonFields.order}` },
      update: { ...lessonFields, content: content as object },
      create: {
        id: `seed-lesson-${lessonFields.unit}-${lessonFields.order}`,
        ...lessonFields,
        content: content as object,
      },
    });

    for (const fc of flashcardData) {
      await prisma.flashcard.upsert({
        where: { id: `seed-fc-${lesson.id}-${fc.front.substring(0, 20)}` },
        update: fc,
        create: {
          id: `seed-fc-${lesson.id}-${fc.front.substring(0, 20)}`,
          ...fc,
          lessonId: lesson.id,
        },
      });
    }

    console.log(`Seeded lesson: ${lesson.title}`);
  }

  // Seed daily challenges
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  await prisma.dailyChallenge.upsert({
    where: { date: today },
    update: {},
    create: {
      date: today,
      type: 'VOCABULARY',
      xpReward: 60,
      content: {
        title: "Daily Vocabulary Challenge",
        description: "Match 10 Spanish words with their English translations",
        pairs: [
          { spanish: "la biblioteca", english: "the library" },
          { spanish: "el aeropuerto", english: "the airport" },
          { spanish: "la farmacia", english: "the pharmacy" },
          { spanish: "el mercado", english: "the market" },
          { spanish: "la panadería", english: "the bakery" },
          { spanish: "el hospital", english: "the hospital" },
          { spanish: "la escuela", english: "the school" },
          { spanish: "el restaurante", english: "the restaurant" },
          { spanish: "la tienda", english: "the store/shop" },
          { spanish: "el banco", english: "the bank" },
        ],
      },
    },
  });

  console.log('Database seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
